### ISSUE TITLE
POST expected data format

### ISSUE THREAD

**Issue by brucelane** [koltyakov/sp-rest-proxy#10]
Hi,
I managed to make GET calls, but I don't know what is expected for a POST:
I tryed to put in your sample: { '__metadata': { 'type': 'SP.DemandesListItem' }, 'Title': 'ok' } but it gives me an error.
I only want to create an item in a Sharepoint 2013 list

Anyway, a big thank you for sharing this!

**Comment by brucelane** [comment]
Hi, no better with { '__metadata': { 'type': 'SP.Data.DemandesListItem' }, 'Title': 'Test' } in 1.1.10
I get a 404 in the console:
```
jquery.min.js:4 POST http://localhost:8080/%7B%20'__metadata':%20%7B%20'type':%20'SP.Data.DemandesListItem'%20%7D,%20'Title':%20'Test'%20%7D 404 (Not Found)
```
Response error:
```
{
  "readyState": 4,
  "responseText": "Cannot POST /%7B%20&#39;__metadata&#39;:%20%7B%20&#39;type&#39;:%20&#39;SP.Data.DemandesListItem&#39;%20%7D,%20&#39;Title&#39;:%20&#39;Test&#39;%20%7D\n",
  "status": 404,
  "statusText": "Not Found"
}
```
Thank you

**Comment by brucelane** [comment]
Does it mean I have to put it on the actual Sharepoint server?

**Comment by brucelane** [comment]
When I run it on the sharepoint server I get:
```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at HTMLButtonElement.<anonymous> (script.js:59)
    at HTMLButtonElement.dispatch (jquery.min.js:3)
    at HTMLButtonElement.r.handle (jquery.min.js:3)
```

**Comment by koltyakov** [comment]
Bruce,

It looks like you are doing something wrong withing your request.
Data object should go to the URL string. It should be a list items endpoint to be provided as a URL.

It works for me in embedded client page:

![](http://koltyakov.ru/images/NewItemRest01.jpg)

and with a $.ajax call:

![](http://koltyakov.ru/images/NewItemRest02.jpg)

```javascript
$.ajax({
   url: '/_api/web/getList(\'/sites/dev01/Lists/Custom02\')/items', 
         // endpoint should be correct one with the exception of the web url
         // which is injected with the proxy automatically from the context setup
   method: 'POST',
   contentType: "application/json;odata=verbose",
   data: JSON.stringify({
       "__metadata": { "type": "SP.Data.Custom02ListItem" },
       "Title": "Created from proxy"
   }),
   success: function(d) { console.log(d); }, 
   error: function(e) { console.log(e.responseText); }
});
```

and on SharePoint page too:

![](http://koltyakov.ru/images/NewItemRest03.jpg)

As you can see, request on the SP page should have some additional setup to include digest, etc., which can be omitted during querying too the proxy.

**Comment by brucelane** [comment]
yes it works!!!!
thank you so much!
now I have to find the way to call it from my ReactJS app

**Comment by koltyakov** [comment]
Always welcome, cheers!
