### ISSUE TITLE
JSOM contextinfo 400 InvalidScope

### ISSUE THREAD

**Issue by rquanx** [koltyakov/sp-rest-proxy#100]
use the same code in spo ,it work on one of my websites,but get InvalidScope in the new websites 

terminal
![image](https://user-images.githubusercontent.com/36622981/80502705-8dce3f00-89a3-11ea-9186-060b4382b35e.png)

private.json
![image](https://user-images.githubusercontent.com/36622981/80502761-9d4d8800-89a3-11ea-853e-c71ae4fd4ecf.png)

response
![image](https://user-images.githubusercontent.com/36622981/80501520-1b109400-89a2-11ea-95b5-cfffb90fc2e1.png)

**Comment by koltyakov** [comment]
Hi there! Are you sure the URL is correct? That `/sites/scs/html/App`. Do you really have 'html' subsite and yet another 'App' subsite? 
Also, the error message looks more like an authentication error. Did you try providing `siteUrl` not to the root site, but site collection?

Authentication is the first thing to check. As dedicated servers and different endpoints are used in China it can have some nuances which never could be seen on our end.

Auth related questions or issues are better target to [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth) repository - the auth library used under the hood.

Also, it could be a good idea to verify if auth works for you in general. I can suggest this [helper repo](https://github.com/koltyakov/node-sp-auth-troubleshoot).

**Comment by rquanx** [comment]
Thanks!

```/sites/scs``` is subsite and ```html/App``` is my local file path.It can work on other spo websites without 'html' and 'App' sub-sites

I try change the local path and provide subsite url to ```siteUrl``` , but get same error
![image](https://user-images.githubusercontent.com/36622981/80556474-40cf8480-8a06-11ea-95f6-5654eb41562a.png)

![image](https://user-images.githubusercontent.com/36622981/80556649-e5ea5d00-8a06-11ea-8d43-23337aa9fab7.png)

I will try to verify if auth works for me later.

**Comment by rquanx** [comment]
Fix in node-sp-auth 2.5.8.
