### ISSUE TITLE
why on demand authentication doesn't show browser window?

### ISSUE THREAD

**Issue by jesuslpm** [koltyakov/sp-rest-proxy#104]
I have setup on demand authentication, but browser window doesn't show.

I asked on StackOverflow [why node-sp-auth on demand doesn't show browser window?](https://stackoverflow.com/questions/61676137/why-node-sp-auth-on-demand-doesnt-show-browser-window). But no answers and no comments. Please help.

**Comment by koltyakov** [comment]
Hi @jesuslpm,

On-Demand auth requires Electron being installed `npm i -g electron@6`.
Electron is optional in node-sp-auth, as it's huge it was an architectural decision making it optional and for manual install only for that rare cases when On-Demand is needed.

**Comment by jesuslpm** [comment]
Hi @koltyakov,

I have Electron v8.2.5 installed globally. Is version 6 required?

**Comment by koltyakov** [comment]
I know that there were some issues with v8 and having troubleshooting it was a quick fix to rollback to v6. Unfortunately, I had no chance to figure out what changed after v6 which brakes On-Demand strategy (there were a couple of cases when each Electron version introduced braking changes) or post an issue to node-sp-auth regarding this.

**Comment by jesuslpm** [comment]
@koltyakov,

Ok, thank you, I'm going to uninstall v8 and install v6 instead. I will come to you when I try it.

**Comment by koltyakov** [comment]
Could you please confirm that rolling back to v6 was a solution for your case?
I'm posting an issue to node-sp-auth to verify if we can make Electron@8 and some previous versions work, and make it a bit more robust or add corresponding notes into the wiki page for On-Demand strategy.

**Comment by jesuslpm** [comment]
@koltyakov .

Yes of course. Just give me a minute.

**Comment by jesuslpm** [comment]
@koltyakov 

Bad luck. Installed Electron v6.1.11 but the browser window doesn't show. I get the error:

```
{
  "readyState": 4,
  "responseText": "Command failed: C:\\WINDOWS\\system32\\cmd.exe /d /s /c \"electron C:\\projects\\MyProject\\node_modules\\node-sp-auth\\lib\\src\\auth\\resolvers\\ondemand\\electron\\main.js https://inercyais.sharepoint.com/sites/dinning-room false\"",
  "status": 400,
  "statusText": "Bad Request"
}

```
 I also executed the following on the command line:

`electron .\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\electron\main.js https://tenant.sharepoint.com/sites/dinning-room false`

But same thing nothing happens. 

Incidentally, UserCredentialStrategy works fine for me. But I would like to make on demand authentication to work. If some day someone decides to activate two factor auth for everyone, i will be annoyed.

Perhaps I'm doing something stupid. But it's the first time I use this proxy and I don't know where to look.

**Comment by nbmarilag** [comment]
Hi,

hope this helps as a quick fix, I install "node-sp-auth" version 2.5.7 on my environment and it works on my end, it seems that it has some issue with node-sp-auth and electron. hope that this issue will be fixed for the upcoming changes.

thanks!

**Comment by s-KaiNet** [comment]
Maybe you have some issues with an electron on your environment.   

Could you try checking it using below `main.js`: 

```javascript
const electron = require('electron');

const app = electron.app;
const BrowserWindow = electron.BrowserWindow;
app.on('ready', () => {
	const mainWindow = new BrowserWindow({
			width: 500,
			height: 650,
			center: true,
			webPreferences: {
				webSecurity: false
			}
		});
	mainWindow.loadURL("http://google.com");
});
```  

run 
```bash
electron main.js
```

Does it open a google window?

**Comment by jesuslpm** [comment]
@s-KaiNet 

Yes, it opens a google window!

**Comment by koltyakov** [comment]
BTW, I bumped the version if sp-rest-proxy, it should use the latest version of node-sp-auth which should support the latest Electron now.

**Comment by s-KaiNet** [comment]
@jesuslpm please try the newer version of sp-rest-proxy, if it doesn't work, then could you answer on a few more questions:
 - in my sample, does it open a window, if you use your sharepoint site url, instead of google.com?
 - which nodejs and electron version do you use
 - which OS
 - which shell do you use to run the process (regular console, vscode built-in shell or smth else)

**Comment by jesuslpm** [comment]
updated sp-rest-proxy to version 2.11.1 and now it works!

Thank you all!
