### ISSUE TITLE
access to simpleserver from lan

### ISSUE THREAD

**Issue by satell** [koltyakov/sp-rest-proxy#108]
I use this for angular sharepoint online proxy and its working fine. But it's only accessible from local host would you please let me know how to access to it from our lan ?

**Comment by koltyakov** [comment]
You can provide `hostname` within the settings object. It's `localhost` by default. `hostname` should be an IP or BIOS Name reachable from within a LAN to enable accessing a proxy from a different machine in the network. But you wouldn't recommend exposing it in a LAN but to force other developers using their own localhost instances instead.

**Comment by koltyakov** [comment]
Going to close this as no response followed.
