### ISSUE TITLE
Request inflated

### ISSUE THREAD

**Issue by slaven-semper** [koltyakov/sp-rest-proxy#109]
I am using Angular 9 in conjunction with sp-rest-proxy and SharePoint 2016 on-premise.

When I make a POST request and include files in it, sp-rest-proxy somehow inflates initial content-length from 300kb to 500kb. This results in incorrect upload operation on the server. I have confirmed it works fine without the proxy.

```javascript
public uploadFile(file: File, projectId: number) {
    const formData: FormData = new FormData();
    formData.append('fileKey', file, file.name);
    formData.append('projectId', projectId.toString());
    return this.httpClient.post(
      pageContext.webServerRelativeUrl + 'Upload.aspx',
      formData,
      { headers: new HttpHeaders({ Accept: 'text/plain' }), responseType: 'text' }
    ).pipe(catchError(_ => {
      return this.showErrorMessage('Error occurred during uploading file on the server.');
    }));
}
```

Is there any configuration option I could use to prevent the proxy from tampering with the request?

**Comment by koltyakov** [comment]
Hi @slaven-semper,

I'd suggest trying the REST API endpoints for document upload.

Can you post a minimal project setup so I could repro and check if this can be amended?

**Comment by slaven-semper** [comment]
> Can you post a minimal project setup so I could repro and check if this can be amended?

Hi! Thank you for your effort.

I fixed it by implementing another router especially for multipart/formdata requests. The problem was with the encoding. I used latin1 for supplying rawbody of bodyParser.raw and then in new parser I created new Buffer object from body while supplying latin1 encoding. I can send you the code if you're interested.

**Comment by koltyakov** [comment]
Going to close this.
