### ISSUE TITLE
v 3.0 doesn't work

### ISSUE THREAD

**Issue by Ne4to777** [koltyakov/sp-rest-proxy#111]
On any request from native ui it throws error: listeners need to be Function, but received Object (see sp-rest-proxy console). v2.11.1 works fine.

**Comment by koltyakov** [comment]
Hi @Ne4to777, 

Can you create a repo there it's reproducible? All tests in v3 run well. And a number of projects in which toolchains we bump the proxy dependency it works.

If it's an existing project, maybe some dependencies stuck. Please try removing node_modules and running npm install.

**Comment by Ne4to777** [comment]
Endpoint (but it doesn't matter):
/_api/web/RegionalSettings/TimeZone.

Error:
 {
  "readyState": 4,
  "responseText": "Proxy Error: The \"listener\" argument must be of type Function. Received type object (see more in sp-rest-proxy console)",
  "status": 400,
  "statusText": "Bad Request"
}

Also throws:
GET https://unpkg.com/@pnp/pnpjs@2.0.2-5/dist/pnpjs.es5.umd.bundle.min.js net::ERR_ABORTED 404 (Not Found)

Settings:
{
 configPath: './dev/private.json',
 hostname: 'localhost',
 port: 8080
}

**Comment by koltyakov** [comment]
PnPjs v2 doesn't come with [ES5 bundle](https://pnp.github.io/pnpjs/concepts/custom-bundle/#create-a-custom-bundle) anymore, the unpkg URL is invalid. Updated CDN links to PnPjs in sample assets, where were @beta/@latest tags in some CDN URLs in samples. However, sample assets do not affect proxy anyhow. They are for quick tests to check if auth works for instance.

As everything works and not reproducible on my end, the recommendation is still the same (remove node_modules & package-lock.json and run npm install). If that doesn't help a minimal scaffolded project for a repro is required to understand what might be wrong. I re-checked on two relatively large codebase production projects and a clean one and can confirm no issues with v3.

**Comment by Ne4to777** [comment]
Clear installation doesn't help. Console:
GET: http://aura.dme.aero.corp/_api/web/RegionalSettings/TimeZone
Error { GotError: The "listener" argument must be of type Function. Received typ                              e object
    at get (C:\Users\asalekseev\dev\vue-master-app\node_modules\got\dist\source\                              request-as-event-emitter.js:200:27)
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at Object.request (http.js:41:10)
    at get (C:\Users\asalekseev\dev\vue-master-app\node_modules\got\dist\source\                              request-as-event-emitter.js:197:65) name: 'RequestError', code: 'ERR_INVALID_ARG                              _TYPE' }

**Comment by koltyakov** [comment]
`Got` dependency is not used for requests proxying but it's what `request-promise` was switched to in `node-sp-auth` v3.
Maybe it's an authentication thing. Can you follow the instructions mentioned in [node-sp-auth-troubleshoot](https://github.com/koltyakov/node-sp-auth-troubleshoot)? 

What authentication strategy you use?

**Comment by Ne4to777** [comment]
NTLM

=== Error ===
 { GotError: The "listener" argument must be of type Function. Received type object
    at get (C:\Users\asalekseev\dev\node-sp-auth-troubleshoot\node_modules\got\dist\source\request-as-event-emitter.js:200:27)
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at Object.request (http.js:41:10)
    at get (C:\Users\asalekseev\dev\node-sp-auth-troubleshoot\node_modules\got\dist\source\request-as-event-emitter.js:197:65) name: 'RequestError', code: 'ERR_INVALID_ARG_TYPE' }

**Comment by koltyakov** [comment]
It's definitely not a proxy thing, but auth-related. And you're saying that node-sp-auth v2 works but v3 doesn't?
I've just checked with NTLM. Works well. Anything weird in private.json? Can you share the structure of private.json, please trim out sensitive data but keep the exact structure including values structure?

**Comment by Ne4to777** [comment]
v2.11.1 works fine just after module reinstall. 

{
	"siteUrl": "http://aura.dme.aero.corp",
	"strategy": "OnpremiseUserCredentials",
	"domain": "dme",
	"siteRelativePath": "/common",
	"siteDisk": "A://",
	"deployPath": "/common",
	"username": "asalekseev",
	"password": "172edd562b087820630e15821c6394d3e02d508a45c73164d3b6997ecacb060ffd3577b4c8973ca6a9f6043c7027b2f0T+PCLRrP3Q1woTsbo8c/wA=="
}

**Comment by koltyakov** [comment]
Config looks well. Got another clue - https://github.com/sindresorhus/got/issues/1071
What Node.js version you're on? Looks that got require at least v10 and a new build.

**Comment by Ne4to777** [comment]
v10.6.0. Updating is not possible now.

**Comment by koltyakov** [comment]
Going to close this.
