### ISSUE TITLE
Receiving 404 when trying to connect for Get method

### ISSUE THREAD

**Issue by georgj42** [koltyakov/sp-rest-proxy#119]
Receiving 404 when trying to connect for Get method.

Seems like Authentication problem. But not sure how to handle.

Error received in the cmd

GET (generic): https://xyz.sharepoint.com/sites/MNPDev/
Error TypeError: Cannot read property 'firstChild' of undefined
    at config_1.request.post.then.xmlResponse (D:\Development\Old code\30-11-2020\MNPDev\node_modules\node-sp-auth\lib\src\utils\AdfsHelper.js:29:69)
    at process._tickCallback (internal/process/next_tick.js:68:7)

![image](https://user-images.githubusercontent.com/74397555/104157104-78edea80-5410-11eb-8fa7-6f9e298f2056.png)

**Comment by koltyakov** [comment]
It's authentication. And from a username I can say an external account is used. External accounts authentication is not supported by authentication library.

**Comment by georgj42** [comment]
What is the alternative here ?

**Comment by koltyakov** [comment]
These options:

- SAML and usual SharePoint Online account (not an external on gmail - Oh, is this an enterprise account, I read cross-out as gmail email) 
- Registering an Add-in
- Try On-Demand auth

To simplify and separate auth related things I'd suggest https://github.com/koltyakov/node-sp-auth-troubleshoot for troubleshooting - it's quicker to check different options and see exact error messages.

The auth related aspects depends on https://github.com/s-KaiNet/node-sp-auth

**Comment by koltyakov** [comment]
Going to close this one and not library related.
