### ISSUE TITLE
CORS Implementation

### ISSUE THREAD

**Issue by ricardo-alvarado** [koltyakov/sp-rest-proxy#123]
I am trying to upload a file to a website and I am obtaining the following error in the console:

**Access to XMLHttpRequest at 'http://localhost:8080/my-web' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.**

At the moment I am using the 3.0.5 version of sp-rest-proxy. In the Response Headers and Request Headers I am obtaining the following:

    Response Headers:
          Access-Control-Allow-Headers: content-type
          Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
          Access-Control-Allow-Origin: *
          Connection: keep-alive
          Content-Length: 0
          Date: Thu, 08 Apr 2021 07:14:39 GMT
          Keep-Alive: timeout=5
          Vary: Access-Control-Request-Headers
          X-Powered-By: Express

    Request Headers
          Accept: */*
          Accept-Encoding: gzip, deflate, br
          Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
          Access-Control-Request-Headers: content-type
          Access-Control-Request-Method: PUT
          Connection: keep-alive
          Host: localhost:8080
          Origin: http://localhost:4200
          Referer: http://localhost:4200/
          Sec-Fetch-Dest: empty
          Sec-Fetch-Mode: cors
          Sec-Fetch-Site: same-site
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36

As you can see, the Origin is "http://localhost:4200" in the request, but the response Access-Control-Allow-Origin is "*". This information makes me think that the origin of this error is in the CORS implementation in sp-rest-proxy.

**Comment by koltyakov** [comment]
Hi there!

The core part, I guess, is "when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute". Not excluding that this can be also resolved with a customisation of the CORS middleware in the proxy, currently it used the defaults.

For the modern toolchains it's better not calling CORS-way but bypass workbench's API endpoint follow to the sp-rest-proxy. In a local workbench, an API request is sent to `/_api`, the local server (Webpack Dev Server, etc.) routes to sp-rest-proxy.

I assume, it's Angular tools? This [article](http://johnliu.net/blog/2017/9/angular-4-sharepoint-on-premises-localhost-development-and-sp-rest-proxy) might be handy.

With a generic Webpack Dev Server the config is [following](https://github.com/koltyakov/sp-rest-proxy#webpack-dev-server).

The advantage of not calling to a separate resource is that no need in code branching (if a localhost use one settings, if deployed another).
