### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by rquanx** [koltyakov/sp-rest-proxy#125]
How can i add this proxy into Vite

**Comment by koltyakov** [comment]
Had no idea what is Vite. Looks like Next.js but for Vue.

Please check [this](https://github.com/vitejs/vite/issues/564). You need to route `/_api` to `sp-rest-proxy` server.

Please note, this is only for the dev, not prod runtime.

**Comment by rquanx** [comment]
I tried to write a plugin for Vite and started it in the buildStart hook, but there was a problem that Vite would restart the server after the modification and the proxy would be created repeatedly to generate `listen EADDRINUSE` error.I added the judgment of whether the port is free, but if I save it quickly modify the file,There will still throw exceptions.

`normal`
![image](https://user-images.githubusercontent.com/36622981/116358513-52718500-a830-11eb-81f2-a8c23ff238cd.png)

`quick edit`
![image](https://user-images.githubusercontent.com/36622981/116358639-7339da80-a830-11eb-923c-9c1a118ae248.png)

**Comment by rquanx** [comment]
publish [rollup-plugin-sp-rest-proxy](https://www.npmjs.com/package/rollup-plugin-sp-rest-proxy) for dev

**Comment by koltyakov** [comment]
Thanks! Going to link your plugin in README.
