### ISSUE TITLE
OData parser to support clients relying on metadata URLs

### ISSUE THREAD

**Issue by koltyakov** [koltyakov/sp-rest-proxy#129]
Add OData metadata parser to POST methods to support some edge cases, such as https://github.com/pnp/pnpjs/issues/1797

**Comment by koltyakov** [comment]
@michaelcmelton, could you please check if sp-rest-proxy@3.1.0 works for your case with addChunked file upload?

**Comment by michaelcmelton** [comment]
@koltyakov  after updating to sp-rest-proxy@latest, seems .addChunked() works as expected. Thanks for the heads up!

**Comment by koltyakov** [comment]
Thanks!
