### ISSUE TITLE
Request Method DELETE

### ISSUE THREAD

**Issue by magnobiet** [koltyakov/sp-rest-proxy#133]
To remove attached files from a list item, SharePoint uses the HTTP method DELETE.

The proxy is returning the following error:

Request Method: DELETE
Request URL: `_api/web/lists/GetByTitle('ListName')/Items(1)/AttachmentFiles/GetByFileName('sample-image.png') `
Status Code: 404 Not Found

```
Cannot DELETE _api/web/lists/GetByTitle('ListName')/Items(1)/AttachmentFiles/GetByFileName('sample-image.png')
```

**Comment by koltyakov** [comment]
Hi there,

SharePoint REST doesn't use DETELE HTTP verb, but POST with X-HTTP-Method: "DELETE" header.

So you're getting 404 as SharePoint API returns 404 as it can't resolve the API call.

Please double check.

**Comment by magnobiet** [comment]
Directly on SharePoint, we are using the DELETE method and works perfectly for this case.

![SharePoint](https://i.imgur.com/YW94gpc.png)

![Proxy](https://i.imgur.com/2thWtPS.png)

If it makes sense for the project to implement the DELETE method will be very useful.

**Comment by koltyakov** [comment]
Oh, didn't know they added non POST methods support. Historically, it was 10+ years POST + X-HTTP-Method.
Will take a look.

**Comment by koltyakov** [comment]
Please check is sp-rest-proxy@3.3.0 works for you?

**Comment by magnobiet** [comment]
Thank you @koltyakov, it works. But, now the response returns a `403 Forbidden`.

We manually copy the `__REQUESTDIGEST` input from the original SharePoint site, but without effect for now.

We continue to investigate that. If you have some idea, we appreciate that.

REQUEST

`Request URL:` https://localhost:4200/.../_api/web/lists/GetByTitle('Components')/Items(1)/AttachmentFiles/GetByFileName('logo.png')
`Request Method:` DELETE
`Status Code:` 403 Forbidden
`X-RequestDigest:` 0x...,19 Nov 2021 11:19:04 -0000

**Comment by koltyakov** [comment]
@magnobiet, could you also try deleting attachment with a common (for SharePoint) approach (https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest)?

**Comment by koltyakov** [comment]
+ sp-rest-proxy@3.3.2 - this should not rewrite a Digest header.

**Comment by magnobiet** [comment]
It's working. Thank you for the quick support.
