### ISSUE TITLE
OndemandCredentials Electron Mac

### ISSUE THREAD

**Issue by tarundhillon** [koltyakov/sp-rest-proxy#135]
Hi 

I have recently changed my dev environment from Windows to Mac and when using OnDemandCredentials strategy I get an electron window stating "Integrated windows authentication isn't supported". I am wondering if there is workaround or configuration which can work on Mac ? 

Thanks
Tarun

**Comment by koltyakov** [comment]
@vladivanovrf when you tried OnDemand strategy last time on a Mac what was a nuance? Specific electron version?

**Comment by vladivanovrf** [comment]
@tarundhillon @koltyakov works fine for me on Mac with electron 11.4.0

**Comment by tarundhillon** [comment]
Thanks both, strange I get the below error with 11.4 also. 

![image](https://user-images.githubusercontent.com/2943230/146390502-739d679a-b4c7-40a3-841d-9f2ee0f3934e.png)

**Comment by koltyakov** [comment]
Hold on. Are you sure that that SharePoint instance is not using NTLM? It won't work with NTLM.

**Comment by tarundhillon** [comment]
I believe so, because the same configuration on Windows was working fine for me. Shifting to mac is resulting into this issue

**Comment by tarundhillon** [comment]
I switched to AdfsUserCredentials which is working fine on Mac, closing this issue. But any ideas around ondemand would be good to know as there there no password change hassles. Thanks
