### ISSUE TITLE
Identical requests - succeeding and failing 

### ISSUE THREAD

**Issue by tarundhillon** [koltyakov/sp-rest-proxy#136]
Hello, 
I seem to be encountering an inconsistent behavior for my sp-rest-proxy setup where identical requests are succeeding and failing. Below is my configuration summary and an example of two requests - fetching value from lists succeeding and failure next to each other. The headers are identical. 

Setup 
{ "siteUrl": "https://xxxxx", "strategy": "AdfsUserCredentials", "username": "xxx", "password": "xxxxx", "relyingParty": "urn:xxx:sharepoint", "adfsUrl": "https://xxx.xxx.com/adfs/ls/", "adfsCookie": "FedAuth"}

Request 1 - Successful 
 
![image](https://user-images.githubusercontent.com/2943230/147217523-059bbd48-0c89-412d-adbf-6ed5232fd6a1.png)

Request 2 - Error Forbidden 
![image](https://user-images.githubusercontent.com/2943230/147217588-07e442bd-8d54-4df5-9ac3-227c3274e516.png)

Any suggestions on what the issue could be or how could I investigate it further ? 

Thanks
Tarun

**Comment by koltyakov** [comment]
So it's requests to the same list getting items and once it works then report a user has no access?

What if to send more requests to this same endpoint, let's say each 5-10 seconds during 1-5 minutes? What will the statistics?

What it to take FedAuth cookie and try multiple requests in Postman, for example?

The only thing I have in mind at the moment is a multiple WFE and a wrong ADFS configuration, and that the first request ended up reaching right WFE, but the second another WFE, maybe.

**Comment by tarundhillon** [comment]
In my main application I am seeing some of the requests intermittently returning 403, so in this test app yes, its the same request fetching items from the list. There is no specific sequence on when things fail or succeed ( or at-least I am not able to find that out) 

> I tried to fire 20 request manually spread over roughly 5-10 seconds each, 8 succeeded & 12 failed. 

For the production setup (code deployed on SharePoint site) tried to use the FedAuth cookie in postman but I am getting a 403 error consistently. I suspect that might be configuration issue in postman, it works intermittently on chrome.

Appreciate there might be multiple issues at play here, but to break it down I am trying to use a simple app to make multiple requests in a dev environment first and understand why things are failing. 


**Couple of questions** 

1. How can I see the FedAuth token for sp-rest-proxy, I tied using   logLevel: 5 &  authConfigSettings: {saveConfigOnDisk:true} but couldn't see more details ? 
 
2. For the adfsUrl setting is it usual to have a trailing "ls" ? Any way of testing this URL ? 

Thanks

**Comment by koltyakov** [comment]
FedAuth cookie can be taken from browser dev tools.

Or with the same creds flow as auth library does, using this helper repo code https://github.com/koltyakov/node-sp-auth-troubleshoot

For ADFS flow, I can recommend checking this material https://github.com/s-KaiNet/node-sp-auth/wiki/ADFS-user-credentials-authentication

**Comment by tarundhillon** [comment]
Thanks ! I have done some further investigations finding below 

1. Node sp auth troubleshoot - configurations works for ADSF and NTML (OnpremiseUserCredentials). Ondemand strangely works on Windows but not Mac. I am able to see FedAuth cookie and it works. Great utility !! Love the ability to maintain different configuration files. 

2. Postman - I am able to fire 30+ requests with FedAuth cookie and no failures at all. That refutes the WFE configuration hypothesis 

Now it leads me to believe that the FedAuth is getting messed up in my App. As next steps I am aiming to monitor which requests are corrupting the FedAuth, I need to find a way to see the the request headers being sent through sp-node-proxy. In the dev environment browser I don't see the cookie, I am assuming that is getting added by sp-node-proxy. 

> Is there a way to monitor the requests being routed through the sp-node-proxy ? 

Wireshark might be my last option, decryption is quite cumbersome. 

Thanks

**Comment by tarundhillon** [comment]
Ignore my initial question, I have cloned the repo and running a local version now. 

I have inserted a log in /router/restGet.ts for the printing the headers (see below), the "cookie" key with FedAuth seems to be missing ? I had to explicitly include this in postman. How is the FedAuth detailed expected to be passed ?

Thanks
Tarun

```
GET: https://xxx/sites/xxx/_api/web/currentuser
Header: Headers {
  [Symbol(map)]: [Object: null prototype] {
    connection: [ 'keep-alive' ],
    'sec-ch-ua': [
      '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"'
    ],
    accept: [ 'application/json;odata=verbose' ],
    'content-type': [ 'application/json;odata=verbose' ],
    'x-requested-with': [ 'XMLHttpRequest' ],
    'sec-ch-ua-mobile': [ '?0' ],
    'user-agent': [
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36'
    ],
    'sec-ch-ua-platform': [ '"macOS"' ],
    'sec-fetch-site': [ 'same-origin' ],
    'sec-fetch-mode': [ 'cors' ],
    'sec-fetch-dest': [ 'empty' ],
    'accept-encoding': [ 'gzip, deflate, br' ],
    'accept-language': [ 'en-GB,en;q=0.9,en-US;q=0.8,fr;q=0.7' ]
  }
}
```

**Comment by tarundhillon** [comment]
Thanks ! 

1. Postman - I managed to successfully send 30+ request without any failures. When the requests are sent from browser I am still getting intermittent failures. Even if there are multiple WFE, it seems very unlikely that all 30 postman runner requests would be successful. 

2. ASFD setup is working fine and validated using the node-sp-auth-troubleshoot (love the multiple configuration file feature). Also validated that FedAuth cookie is being set and passed properly by sp-rest-proxy. 

On the server end, below snapshot shows the success and failure trace. 

![image](https://user-images.githubusercontent.com/2943230/147419174-a736b47d-2bda-4917-a99e-5a44c1325923.png)

This clearly is an authorisation issue at sever end and not related to sp-rest-proxy so closing this issue. If you have suggestion on potential causes (especially point 1) , that would be great. 

Thanks for your help. BR
