### ISSUE TITLE
sharepoint MFA bypass

### ISSUE THREAD

**Issue by mamoussa405** [koltyakov/sp-rest-proxy#144]
Hello, how i can bypass MFA to connect to sharepoint with sp-rest-proxy???

**Comment by koltyakov** [comment]
Hi @mamoussa405,

It's not possible to bypass a security limitation however there are some approaches.

- Use account with disabled MFA
- Use an Add-In authentication strategy (some APIs won't work with Add-Ins though).
- Use On-Demand strategy and enter MFA code in the popup window
- Create [app password](https://support.microsoft.com/en-us/account-billing/manage-app-passwords-for-two-step-verification-d6dc8c6d-4bf7-4851-ad95-6d07799387e9)

**Comment by mamoussa405** [comment]
okay thanks Sir, i'll try them.
