### ISSUE TITLE
sp-rest-proxy with sharepointplus

### ISSUE THREAD

**Issue by mamoussa405** [koltyakov/sp-rest-proxy#146]
Hello,
how i can use sp-rest-proxy with sharepointplus library in react js??

**Comment by mamoussa405** [comment]
okay thank you Sir

**Comment by mamoussa405** [comment]
Hello Sir,
i didn't want to open i new issue, but i have a problem with sp-rest-proxy and i don't know what is the reason, the problem is the sp-rest-proxy works fine but after a while a killed the server with sigInt signal and i started it again, but when i make a request it gives the prompt to inter the credentials (On-Demand credentials) but instead of requesting the credentials it renders the  home page of the sharepoint site, any idea about that??. Thanks in advance.

**Comment by koltyakov** [comment]
Hi @mamoussa405,

This might be connected with Electron version.

https://github.com/s-KaiNet/node-sp-auth/issues/79

Please check if it works for you with Electron 8 or 9?

**Comment by mamoussa405** [comment]
i have v18.2.3 is that the problem??

**Comment by koltyakov** [comment]
Going to close this as the reopened part related to a separate auth topic. Which also was started in node-sp-auth repo.
