### ISSUE TITLE
Problem Uploading File to Document Library

### ISSUE THREAD

**Issue by ismet** [koltyakov/sp-rest-proxy#17]
Hi,

I cannot add a file into a document library. The errors are similar to what we had in adding file attachments:  HTTP 403 (Bad request), HTTP 413 (Payload too large)

Sample code (using sp-pnp-js),
```
web.getFolderByServerRelativeUrl("/MyDocumentLibrary/").files.add(fileName, fileData, true);
```

**Comment by koltyakov** [comment]
Also was thinking about this. Unfortunately, it's not a silver bullet to make switching between express middlewares (at least I didn't find a universal way).
Likely, it's identical to attachment case #15.
Have extended regular expression to the route with raw body parser to take care about /files/add.
The parameter for body size is the same `rawBodyLimitSize`. But, for json payload, a parameter also was added, `jsonPayloadLimitSize`.

P.S.
The documentation is really out of date after last changes. The good thing is that the code base was migrated to TypeScript, which is by itself in some way is a documentation.

**Comment by koltyakov** [comment]
Quick manual tests for document upload are integrated to the page `http://localhost:8080/test/documents.html`. 
Closing the issue. Feel free to reopen if I forgot something and there is still something not working.
