### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by dreamworks** [koltyakov/sp-rest-proxy#173]
Hi,

I tried the docker-hub image, but it's failing (see screenshot); reason is that node v16 seems to be required. 
Used a local Dockerfile with "FROM node:16-alpine" instead and authentication was working again..

![Clipboard01](https://github.com/koltyakov/sp-rest-proxy/assets/432356/0d151415-bba3-4aaf-a6c9-75118c37b686)

**Comment by koltyakov** [comment]
Thank you @dreamworks for catching this up.
Can you check if the pushed docker image update works for you OOTB.

**Comment by dreamworks** [comment]
Yup.. This time it works perfectly..Thx a lot!
