### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by dinogit** [koltyakov/sp-rest-proxy#30]
Hi,

I have problem when trying to get request from Sharepoint.
I did git clone project, built it, serve it and added credentials. After that I get this : 
![error](https://user-images.githubusercontent.com/1814086/31515285-efd411d4-af94-11e7-958d-ec91baae884f.png)

Error point to script.js:58.

Thanks in advance and thanks for creating this plugin.

**Comment by koltyakov** [comment]
Hi there @dinogit,

Can you try using relative URLs starting with '/'? 
E.g. '/_api/web' not '_api/web'.

**Comment by dinogit** [comment]
Hi @koltyakov 

tried that first, it didn't work

![image](https://user-images.githubusercontent.com/1814086/31516140-c31eaec6-af97-11e7-81f5-bf46e4939e8a.png)

How can I check if authentication succeeded?

**Comment by koltyakov** [comment]
I've just checked `_api` and `/_api` both works for me, I even forgot that this. =)

You can check if auth works by creating `authCheck.js` in project's root folder with:

```javascript
const AuthConfig = require('node-sp-auth-config').AuthConfig;
const spauth = require('node-sp-auth');

const authConfig = new AuthConfig({
    configPath: './config/private.json',
    encryptPassword: true,
    saveConfigOnDisk: true
});

authConfig.getContext()
    .then(context => {
        return spauth.getAuth(context.siteUrl, context.authOptions);
    })
    .then(options => {
        console.log(options);
    })
    .catch(error => {
        console.log(error);
    });
```

and running:

```bash
node ./authCheck
```

If auth is ok, then there should be something like this:

![image](https://user-images.githubusercontent.com/7816483/31517048-54548a86-afa3-11e7-8529-9185b170fb29.png)

or an error if something wrong with the creds or network or something. E.g.:

![image](https://user-images.githubusercontent.com/7816483/31517092-7e5054f0-afa3-11e7-90f4-b590c7f632a7.png)

**Comment by koltyakov** [comment]
What auth type are you using, what is the version of SharePoint?
I can see that it's on-premises, some auth could have been provided wrong.

**Comment by dinogit** [comment]
hm... got same message
```
sp-rest-proxy master ✗ 4d ◒ ➜ node ./authCheck
TypeError: callback is not a function
    at Object.parseType2Message (/Users/dino/Sites/sp-rest-proxy/node_modules/httpntlm/ntlm.js:116:3)
    at request.then (/Users/dino/Sites/sp-rest-proxy/node_modules/node-sp-auth/lib/src/auth/resolvers/OnpremiseUserCredentials.js:36:33)
    at tryCatcher (/Users/dino/Sites/sp-rest-proxy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dino/Sites/sp-rest-proxy/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/dino/Sites/sp-rest-proxy/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dino/Sites/sp-rest-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dino/Sites/sp-rest-proxy/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/dino/Sites/sp-rest-proxy/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/dino/Sites/sp-rest-proxy/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/dino/Sites/sp-rest-proxy/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

It Sharepoint 2013, authentication is handled by Forefront TMG

**Comment by koltyakov** [comment]
Hmm, I'm not sure that `node-sp-auth` (authentication module) works with TMG.
What a coincidence! I was going to test it with TMG upcoming days on one of the projects and environment access to which I do not have yet.

@dinogit, could you please try On-Demand and FBA scenarios? To do it, just rename `./config/private.json` to something else and run the proxy or authCheck again and chose these strategies:

![image](https://user-images.githubusercontent.com/7816483/31518488-18b64b22-afa8-11e7-9844-d433f3c561fc.png)

FBA is likely won't work (it would be crazy, but please try it too).
On-Demand auth should open browser window in electron for input. On-Demand auth can't work with NTLM, but when using TMG... maybe there a tiny chance. =)

If nothing of these won't work, stay tuned!

@s-KaiNet, just wondering, have you ever had a chance to test `node-sp-auth` with TMG? If not and existimg auth scenarious don't work probably I'll create PR, as for my task I got a lot of work with environment behind TMG.

**Comment by dinogit** [comment]
Hi @koltyakov 

I have test it and it's not working, receiving sam error.

Thank you very much for your time tonight and looking forward to see progress with environment behind TMG.

**Comment by s-KaiNet** [comment]
The only option which might work is ondemand scenario.    
At least it works for [this configuration](http://www.sharepoint4developers.net/en-nz/post/wap-adfs-sp2013-kerberos.aspx), so that's a big chance it will work for TMG.   
@dinogit have you tried [on-demand](https://github.com/s-KaiNet/node-sp-auth/wiki/On-demand-authentication) option?

**Comment by koltyakov** [comment]
@s-KaiNet, thanks! We will know it for sure tomorrow when I got to get my hands dirty with TMG on the project I mentioned above.

**Comment by dinogit** [comment]
hi @s-KaiNet , when using on-demand option, after successful login and hitting submit button, it displays "Loading..." and just stays like that. There are no errors in console.

**Comment by s-KaiNet** [comment]
Where does it display loading? Can you please post a screen?

**Comment by dinogit** [comment]
![image](https://user-images.githubusercontent.com/1814086/31540097-ef2ac5cc-b00a-11e7-9606-821a0473f693.png)

**Comment by dinogit** [comment]
![image](https://user-images.githubusercontent.com/1814086/31540121-06a620ca-b00b-11e7-97a6-6dde35e5ab81.png)

**Comment by koltyakov** [comment]
Hey guys,

I've figured out and implemented new auth strategy for SharePoint (or actually any website) behind Forefront TMG reverse proxy.

Created a PR https://github.com/s-KaiNet/node-sp-auth/pull/17 to `node-sp-auth` project, hope the merge process will be smooth.

**Comment by koltyakov** [comment]
Hey @dinogit,

Can you try newly added auth scenario for SharePoint behind TMG?

To do it you should update `node-sp-auth` and `node-sp-auth-config` by:

Deleting `node_modules` folder and `yarn.lock` or `package-lock.json` (to avoid possible packages collisions),

and running

```bash
npm i node-sp-auth node-sp-auth-config --save-dev
```

inside a project.

_Or it's even better to install sp-rest-proxy 2.4.0 - it contains updated dependencies._

Then delete or rename `./config/private.json`, run `node ./authCheck` and choose `Forefront TMG authentication`:

![image](https://user-images.githubusercontent.com/7816483/31567350-c35a3398-b077-11e7-9d81-7fd225bf7cd5.png)

Auth cookie should be in the following format:

![image](https://user-images.githubusercontent.com/7816483/31565072-18d73924-b06e-11e7-8c95-f19fddfcc5c3.png)

I was managed to run few tests with proxy and a new auth method on the environment I have. Everything worked for me. Hope the same on your end. =)

**Comment by dinogit** [comment]
Hi @koltyakov 

I am getting error when trying to build project

![error](https://user-images.githubusercontent.com/1814086/31630175-27724e02-b2b6-11e7-9ded-71a163f5ea86.png)

**Comment by koltyakov** [comment]
It's an issue in @types/request-promise declarations, just can be ignored.

**Comment by dinogit** [comment]
Hi @koltyakov I have updated yarn and it's working
