### ISSUE TITLE
Angular 4 and SharePoint On-Premise

### ISSUE THREAD

**Issue by dafabulousteach** [koltyakov/sp-rest-proxy#31]
This is more of a question than an issue

I set up the proxy according to the instructions and placed my credentials in the __private.conf file.
The __private.conf looks like this:
```
{
  "siteUrl": "https://my_company_SP_site",
  "username": "[username]",
  "password": "[password]",
  "domain": "[our domain]",
  "workstation": "" // don't have this
}
```
 I have a service in Angular that is calling the SP REST API endpoint of 
```https://my_company's_site/_api/web/lists/GetByTitle(\'categories\')/items?$filter=level%20eq%201&$select=Title```

It looks similar to this:
```
private _landingPageUrl = 'https://my_company's_site/_api/web/lists/GetByTitle(\'categories\')/items?$filter=level%20eq%201&$select=Title';
getMajorCategories(): Observable<any> {
    const headers = new Headers({
      'Accept': 'application/json;odata=verbose',
    });
    const options = new RequestOptions({headers: headers})
    return this._http.get(this._landingPageUrl)
    .do(data => console.log('Categories are: ' + JSON.stringify(data)))
    .catch(this.handleError);
  }

```
When I attempt to call that service, I am receiving a 403 error that localhost is not allowed access. What should I be I forwarding to my proxy.conf.json file? I followed the set up found in [this blog post by John Liu](http://johnliu.net/blog/2017/9/angular-4-sharepoint-on-premises-localhost-development-and-sp-rest-proxy)

**Comment by koltyakov** [comment]
Hey Kim,

Thanks for the question.
In addition to the conversation in [Gitter chat](https://gitter.im/sharepoint-node/Lobby) adding some info here:

Some facts:
- The proxy can be started as a separate local server on its port (8081, etc.)
- Front-end code can be served with the tool of choice (ng server, webpack serve, gulp, grunt, local express, anything) on its port different from the proxy's server (e.g. 8080)
- The proxy also supports hosting local static files (so an app can be served with proxy's server itself), but most prefer Angular way in this case integrated CORS come into play
- The developed app should have two modes - for a local serve and production mode; local server should point all API calls to proxy, prod mode - relative SharePoint paths

Misc:
- `__private.conf.json` should not be created manually, on proxy start a wizard-like interface prompts for auth strategy and creds
- If an app is targeted to a subweb, it's better to point `siteUrl` to the web
- Accept headers should be passed to the requests in the same manner as being on the SharePoint page
