### ISSUE TITLE
Add end-to-end example for Angular

### ISSUE THREAD

**Issue by koltyakov** [koltyakov/sp-rest-proxy#33]

**Comment by koltyakov** [comment]
[Angular 4, SharePoint On-Premises, localhost development and SP-REST-Proxy](http://johnliu.net/blog/2017/9/angular-4-sharepoint-on-premises-localhost-development-and-sp-rest-proxy)

**Comment by Draghonite** [comment]
Thank you for the library.  Sadly, despite following these great examples, I still could not get integration with a standalone SP instance.  Using jQuery for the moment but keeping an eye on this library.

**Comment by koltyakov** [comment]
Hi @Draghonite, thank you for your message and the interest.
You can definitely use sp-rest-proxy with jQuery.ajax or even raw XMLHttpRequest or Fetch.
In your local dev server, requests should be targeted to proxy's endpoint. And in the code, based on if it's a local environment or not http client wrapper should decide where to target requests in a runtime.

**Comment by nsksaisaravana** [comment]
@koltyakov Thanks a lot for your hardword, there should be simple way to program in Angular 5+ , PnpJS inside sharepoint classic page or SPFX. I heard Microsoft is going to come up with a page where we can develop Angular SPA !!!!!

**Comment by Gopinath83** [comment]
@koltyakov Thanks a lot for finding out SP proxy to handle the SharePoint REST APIs.
I have tried the [http://johnliu.net/blog/2017/9/angular-4-sharepoint-on-premises-localhost-development-and-sp-rest-proxy](url) article but i could not able to make it.
I'm using Angular 7 with SharePoint 2013. We are not using SPFx.  

Could you please let us know if you have step by step guide to configure the SP-REST-Proxy in Angular 7 environment. 

Thanks

**Comment by koltyakov** [comment]
Hi @Gopinath83,

Thanks for using the library!

Not being Angular user it's difficult to provide you an optimal way. I have no clue in many Ng configs and decisions they made in their generator. Followed the recent docs and created this as a walkthrough mini guide:

```bash
npm install -g @angular/cli

ng new ng-sp-proxy
cd ng-sp-proxy

npm i -D sp-rest-proxy

touch proxy.conf.js
```

```javascript
const port = 9090; // better using env var

const PROXY_CONFIG = {
  '/_api/*': {
      target: `http://localhost:${port}`,
      secure: true
  }
};

module.exports = PROXY_CONFIG;
```

Add "proxyConfig": "proxy.conf.js" to angular.json 

```bash
touch proxy.api.js
```

add:

```javascript
const RestProxy = require('sp-rest-proxy');

const port = 9090; // better using env var
const configPath = './config/private.json';

const settings = { configPath, port };

const restProxy = new RestProxy(settings);
restProxy.serve();
```

Add npm task or run `node ./proxy.api.js` (enter creds on the first run).

Run `npm run start` and `node ./proxy.api.js` simultaneously.

If you know how to reconfigure web pack dev server options in Ng CLI (I have no idea) when [this](https://github.com/koltyakov/sp-rest-proxy#webpack-dev-server) approach is preferred (no parallel tasks are required, tighter integration with dev server).

Use [loadPageContext](https://github.com/koltyakov/sp-rest-proxy#load-page-context-helper) as a context helper to use _spPageContextInfo in a local serve mode.

P.S.

If you'll end up with a guide which works for you it would be cool if you can contribute with the corresponding angular config doc. In case you're blogging, would love to add a link to a blog post with Angular 7 + Proxy configuration instruction. Thanks!

**Comment by mgordic** [comment]
Hi @koltyakov,

I followed your instruction how to setup Angular project to use sp-rest-proxy.

However, I have some issues there:

1.  loadPageContext() is executed, and _spPageContextInfo is filled in. There I see for example that webAbsoluteUrl is http://localhost:4200/sites/test

2. When I next try within loadPageContext to query sharePoint data, I am getting Http 404 error, since it's making request to localhost:4200/sites/test. Proxy itself is working, when I make a request trough it, I am getting results back from SP.

Do you have any idea what could be wrong here?

It's funny that it's working like a charm in react, but seems so Angular's proxy is making some problems here.

**Comment by koltyakov** [comment]
Hi Marko,

I and Angular are on the different side of the road. ;)
The only can suggest in this situation is to start proxy and Angular dev server in parallel and configure code with "if localhost then send API calls to proxy otherwise to current hostname".

**Comment by mgordic** [comment]
Hi Andrew,

Thank you! That's exactly what I did in meantime.

`ngOnInit()
  {
    let self = this;

    loadPageContext().then(async s =>
    {
      sp.setup({
        sp: {
          headers: {
            Accept: "application/json;odata=verbose"
          },
          baseUrl: self.isLocalDevMode() ? 'http://localhost:9090' : _spPageContextInfo.webAbsoluteUrl
        }
      });

      sp.web.select("Title").get().then(w =>
      {

        console.log(w.Title);

        self.title = w.Title;
      }).catch((err) => { console.log(err); });

    }).catch((err) =>
    {
      console.error(err);
    });
  }`

`public isLocalDevMode()
  {
    return window.location.href.indexOf('localhost') >= 0;
  }`

What I don't understand here is why do I need loadPageContext, when it returns anyway wrong url (it's returning url that is localhost + server relative url of target SharePoint site.

My understanding is that when I call this url, in background it will intercept that call and pass it trough proxy to get data from SharePoint. If I leave it without setting up base url with proxy address, then every call to pnpjs will fail.

Have you see maybe this before?

Thank you
Marko

**Comment by koltyakov** [comment]
One moment:

![image](https://user-images.githubusercontent.com/7816483/61027031-bf96fa80-a3bd-11e9-99bd-67db649aaea4.png)

It's better placing absolute URL which corresponds to a real site abs URL, e.g. if your site is `https://c.sharepoint.com/sites/something`, proxies URL should be `http://localhost:port/sites/something`, but not just `http://localhost:port`. Even while proxy will understand and add the relative part, I recommend mirror the URLs this way.

> What I don't understand here is why do I need loadPageContext, when it returns anyway wrong url (it's returning url that is localhost + server relative url of target SharePoint site.

It's made for a scheme where Webpack Dev server's proxy bypasses API calls to sp-rest-proxy. This schema ends up with the same localhost origin for SPA static assets and API.
When configured properly, `loadPageContext` not only gives an absolute URL, but a part of the `_spPageContextInfo` such as user info, language to name just a few.

The method works well but this the assumption that first API hostname is the same as the one dev assets hosted on:

![image](https://user-images.githubusercontent.com/7816483/61027776-ab53fd00-a3bf-11e9-9d24-e3407a80ef4f.png)

And I sure that an Angular project (scaffolded with CLI) can be theoretically configured identically as those majority of React apps there we just [extend DevServer with before handler](https://github.com/koltyakov/sp-rest-proxy#webpack-dev-server) or any framework with a custom Webpack config and Dev Server as well, but taking a look into what Ng CLI scaffolds I didn't get the idea how.

**Comment by Gopinath83** [comment]
Hi Marko,

I was trying to set up sp-resst-proxy due to some other environment issue I couldn’t able to achive.
If you had already set up and able get “_spPageContextInfo” It will be great if you could share the code or GitHub project it will really help me to configure angular project in SharePoint box.

Regards,
Gopinath V
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
