### ISSUE TITLE
JSOM support documentation

### ISSUE THREAD

**Issue by amadeogallardo** [koltyakov/sp-rest-proxy#34]
Hi,

Is there any documentation on how to configure sp-rest-proxy to support JSOM operations?
The rest of the operations are working just fine (amazing work!!!): REST, Lists.asmx, ListData.svc but, for some reason, JSOM requests are not proceeding.

Thanks!

**Comment by koltyakov** [comment]
Hi @amadeogallardo,

JSOM/CSOM requests are the POST requests with XML body to /_vti_bin/client.svc/ProcessQuery endpoint.
If a correct XML body is sent to the proxy it processes with it correctly.
But to make it work environment page, from which JSOM calls should be sent to the proxy, should be patched with JSOM's JavaScripts like:
- {{lcid}}/initstrings.js
- init.js
- msajaxbundle.js
- sp.core.js
- sp.runtime.js
- sp.js
Also, some global variables should be [mimic](https://github.com/koltyakov/sp-jsom-node/blob/master/src/JsomNode.ts#L85) (it's a Node version of mimicing SharePoint page).

I was thinking about creating a workbench page or a script which would load JSOM to a page from Proxy, but there was no demand from the community yet.

Maybe I'll do it someday.
If you'll be trying adding scripts manually with some success your input/feedback is welcome.
Btw, static resources also can be requested via proxy.

**Comment by amadeogallardo** [comment]
Thanks, will use that as a starting point and post any findings.

**Comment by koltyakov** [comment]
https://github.com/koltyakov/sp-rest-proxy#jsom-sharepoint-javascript-object-model

**Comment by koehrlenguillaume** [comment]
Hi @koltyakov 

I tried to use your project to save dev time ! 
Regarding my create-react-app project, I cannot use pnpjs that why I'm trying to use the JSOM version of your proxy. 

I set all the settings as you said and the proxy works on all the REST requests. 
However, when I added the following snippet in my index.html, I had issues. 

Snippet: 
```html 
<script type="text/javascript" src="/_layouts/15/1033/initstrings.js"></script>
<script type="text/javascript" src="/_layouts/15/init.js"></script>
<script type="text/javascript" src="/_layouts/15/MicrosoftAjax.js"></script>
<script type="text/javascript" src="/_layouts/15/sp.core.js"></script>
<script type="text/javascript" src="/_layouts/15/sp.runtime.js"></script>
<script type="text/javascript" src="/_layouts/15/sp.js"></script>
```

Issues: 
<img width="1077" alt="screenshot 2018-10-22 at 19 03 06" src="https://user-images.githubusercontent.com/6214839/47306585-248ea280-d62d-11e8-87f6-2ec964a2cb31.png">

I tried to run the get request through the proxy interface and have the following message: 
<img width="1153" alt="screenshot 2018-10-22 at 19 04 29" src="https://user-images.githubusercontent.com/6214839/47306656-543daa80-d62d-11e8-8d1a-743f5b800b8d.png">

Do you have any idea or tips to debug ? 

Thanks!

**Comment by koltyakov** [comment]
Hi @koehrlenguillaume,

The difference in URLs should be taken into consideration. Local dev server and proxy addresses, depending on the configuration, can be different, e.g. CRA dev server is started on `http://localhost:3000` and the proxy's on `http://localhost:8080`.

SP JS resources should be targeted to the proxy's endpoint, the same thing as with the requests unless the dev server is configured to relay API and some static resources requests to sp-rest-proxy's server.

The good idea is to check if there is any log output in the node console where the proxy is running. Static resources requests are logged too. Otherwise, the URLs are routed somewhere else.

**Comment by koehrlenguillaume** [comment]
Thanks for your answer, I was thinking that all request executed against the `http://localhost:3000` are automatically redirected to the proxy. 
That why we have the static root specified in the server settings right ? 
```javascript
const RestProxy = require('sp-rest-proxy');

const settings = {
  port: 8081,
  configPath: './config/private.json',
   staticRoot: './static'
  debugOutput: true,
};

const restProxy = new RestProxy(settings);
restProxy.serve();
```

Currently in my node console, I only have the requests made to my onPrem SharePoint. At this point it looks ok. 

I did more research with fiddle and I have the impression it's related to the language. 
For example: If I change the locale for the initstrings.js from english to french, it works. However, I don't how to do the same on the others files yet. 
```html 
  <script type="text/javascript" src="/_layouts/15/1033/initstrings.js"></script>
````
```html
  <script type="text/javascript" src="/_layouts/15/1036/initstrings.js"></script>
```

Maybe that's related to some header, do we have a way to edit it ? 

I saw in your code that we have some log level, can you tell me the correct way to use it ?

**Comment by koehrlenguillaume** [comment]
Thanks I found my problem with your explanation 👍 
I didn't get that all js files has to be saved in the local project. I was thinking that we can load all js files from the remote SP through the proxy server. 

In all case, thanks for your outstanding work ! It's going to save me a lot of time

**Comment by koltyakov** [comment]
> I was thinking that we can load all js files from the remote SP through the proxy server.

This is correct, on the screenshot above all the JSOM JavaScripts are hosted directly from SharePoint site. They should not be downloaded, yet anyway, it's also an option.
