### ISSUE TITLE
File Upload Fails

### ISSUE THREAD

**Issue by airportyh** [koltyakov/sp-rest-proxy#35]
We have had issues with uploading files through the sp-rest-proxy. It happens both for uploading to a document folder as well as for uploading an attachment. The error reads:

```
Cannot read property 'byteLength' of undefined
```

Here is a screenshot with more details:

<img width="731" alt="screen shot 2017-11-16 at 8 08 53 am" src="https://user-images.githubusercontent.com/54303/32892890-ad1adaa4-caa5-11e7-817a-a095fe8f114c.png">

**Comment by koltyakov** [comment]
Hi Toby,

Can you check the following:
- Run sp-rest-proxy (without your PR)
- Navigate to `http://localhost:8080/test/documents.html`
- Try document and attachment upload

![image](https://user-images.githubusercontent.com/7816483/32893544-f8f025f2-caea-11e7-901f-ac4fc97b3926.png)

Does it work for you?

**Comment by koltyakov** [comment]
Toby,

Could you please check if the version 2.4.2 with your PR merged works for you?

**Comment by Wireliner** [comment]
Hello @koltyakov 

I have the same problem when uploading image. Tried with versions 2.5.0, 2.4.2 and 2.4.1

> Cannot read property 'byteLength' of undefined

`return this.http.post(
     this.getUrlImageListItems(item.imageListName, item.image.Filename),
         item.image.ArrayBuffer,
         { headers: new HttpHeaders()
        .set('accept', 'application/json;odata=verbose')
        .append('X-RequestDigest', item.fdv)
        .append('content-type', 'undefined')
        }
);`

**Comment by koltyakov** [comment]
Hey @Wireliner, will take a look.

**Comment by Wireliner** [comment]
@koltyakov I tried POST with jQuery and it worked

`return $.ajax({
                            url: this.getUrlImageListItems(item.imageListName, item.image.Filename),
                            type: 'POST',
                            data: item.image.ArrayBuffer,
                            processData: false,
                            headers: {
                                'accept': 'application/json;odata=verbose',
                                'X-RequestDigest': item.fdv
                            },
                            sucess: (res) => res,
                            error: (err) => err
                        });`

<img width="573" alt="jquery" src="https://user-images.githubusercontent.com/22619894/33485230-6f656480-d6c7-11e7-8f10-7d628e5819f0.png">

however, the angular5 HttpClient POST request does not, as I mentioned earlier. These 2 request fail: 

`return this.http.post(
                            this.getUrlImageListItems(item.imageListName, item.image.Filename),
                            item.image.ArrayBuffer,
                            { headers: new HttpHeaders()
                                .set('accept', 'application/json;odata=verbose')
                                .append('X-RequestDigest', item.fdv)
                            }
                        );`

`return this.http.post(
                            this.getUrlImageListItems(item.imageListName, item.image.Filename),
                            item.image.ArrayBuffer,
                            { headers: new HttpHeaders()
                                .set('accept', 'application/json;odata=verbose')
                                .append('X-RequestDigest', item.fdv)
                                .append('processData', 'false')
                            }
                        );`

**Comment by koltyakov** [comment]
> angular5 

Good point for troubleshooting.
I'm in a bit rush this evening so will be able to check with Angular 5 later tonight or tomorrow.

Thanks!

**Comment by Wireliner** [comment]
@koltyakov thanks a lot! 

when I do POST from SP it works both with jQuery and angular5.

**Comment by koltyakov** [comment]
Was managed to reproduce the error with Angular.
Also, have a situation with uploading code working on SP page and not working via proxy.
Good sign... now figuring out and fixing it...

**Comment by koltyakov** [comment]
A workaround is to provide 'Content-Type' header, e.g. `.append('Content-Type', 'application/json;odata=verbose')`.

**Comment by koltyakov** [comment]
Finally, I was managed to fix it.
@Wireliner, please try with v 2.5.1.
It should work with your existing setup.
I'm a complete newbie with Angular. Was tested on [this project](https://gitlab.com/spnode-public/sp-proxy-angular).

**Comment by Wireliner** [comment]
Great job! @koltyakov 
Confirmed. Image upload works with Angular 5 HttpClient. Thank you!

**Comment by koltyakov** [comment]
Cool! Closing the issue.
