### ISSUE TITLE
Cant seem to download files from sharepoint?

### ISSUE THREAD

**Issue by stephen-walsh** [koltyakov/sp-rest-proxy#37]
I've been trying to get this working, 
For example i'd use the following REST URL

`/sites/<COMPANY>/_api/web/GetFileByServerRelativeUrl('/sites/<COMPANY>/Shared Documents/test doc.docx')/$value`

and the sp-request will correctly pull down the data.
However the conversion to the expressjs response seems flawed.

I'd added in code to copy all the headers from sp-request to the expressjs response
this has aided a bit - The proxy is now sending by the correct content type.

But i believe the body of the response is not correct. I've tried 
`res.end(response.body, 'binary');`
without much luck. (this replaced the `res.json(response.body);`

Steve

**Comment by koltyakov** [comment]
Hi Stephen,

I’ll take a look. Intehration tests include document and attachment upload, but I haven’t ever tried download via proxy. 

Will test it with sp-download and sppull. :)

**Comment by stephen-walsh** [comment]
thanks koltyakov,

I did place this pieces of code in the sp-request response fucntion

```
          var file = fs.createWriteStream("/Users/stephen/Desktop/test.docx");
          var path = '/Users/stephen/Desktop/test.docx'
          fs.writeFile(path, response.body, function(err){
            console.log("Error in Download to File,"+err);
          });
          console.log("File Downloaded");
```

It did download and save the file, but it wasn't saved correctly (corrupt file)
So bottom line is that the sp-request isn't downloading the files correctly.

**Comment by stephen-walsh** [comment]
playing around with the sp-download

`const cpass = new Cpass();
    let context: IAuthOptions;
    context = require(path.resolve("./config/private.json"));
    (context as any).password = (context as any).password && cpass.decode((context as any).password);
    const download = new Download(context);

    let filePathToDownload: string = "https://<SITE>.sharepoint.com/sites/<Company>/_api/web/GetFileByServerRelativeUrl('/sites/<Company>/Shared Documents/test doc.docx')/$value";
    let saveToPath: string = '/Users/stephen/Desktop';
    

    download.downloadFile(filePathToDownload, saveToPath)
      .then(savedToPath => {
        console.log(`Has been downloaded to ${savedToPath}`);
      })
      .catch(error => {
        console.log(error);
      });`

And i get 
`400 - {"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The expression \"web/GetFileByServerRelativeUrl('/sites/ChatSpace/Shared Documents/_api/web\" is not valid."}}}`

**Comment by koltyakov** [comment]
`filePathToDownload` stands for file url, not the REST endpoint.
If you copy a link in a browser - this will be a correct URL to pass to sp-download.

**Comment by stephen-walsh** [comment]
Hugh thanks for the quick reply koltyakov!!

Just tried this as the URL (its a link to "test doc.docx")

`https://<SITE>.sharepoint.com/sites/<COMPANY>/_layouts/15/download.aspx?guestaccesstoken=JKSOWebPd9r56na9AoE5fGqTKMv8fx2c9ofbdttVAMw%3D&docid=2_10093c7fbe60b4a2a947cf061e76d7ab6&rev=1&e=7d2b3d6a419f448c808e09ca53cc0358`

It downloaded a something and named it` download.aspx?guestaccesstoken=JKSOWebPd9r56na9AoE5fGqTKMv8fx2c9ofbdttVAMw=&docid=2_10093c7fbe60b4a2a947cf061e76d7ab6&rev=1&e=7d2b3d6a419f448c808e09ca53cc0358`

after i renamed it back to `test doc.docx`, it was clear that the file didn't download correct :(

**Comment by koltyakov** [comment]
That's not a document url too =))

![image](https://user-images.githubusercontent.com/7816483/33391923-995cdd0e-d54b-11e7-8468-bd0405e5964e.png)

So the url to the document/file should be `https://hostname/sites/site/web/library/folder/subfolder/filename.ext`

**Comment by koltyakov** [comment]
Actually, what you use in `GetFileByServerRelativeUrl` but with absolute path.

**Comment by koltyakov** [comment]
So I was managed to check.
I run sp-rest-proxy and target sppull (the library we use for batch downloading, it shares the same principal as sp-download) to the proxy's path.
All the document and folders have been downloaded successfully. Beneath the documents are text, images and office documents, all of them are with correct encoding, can be opened.

I'm wondering, what was your initial goal?

Some comments:
- sp-rest-proxy is a tool for toolbelting SPA applications dev toolchain with CORS API for local development
- sppull - is a good chose when a set of documents should be downloaded, e.g. target a folder and download everything within it
- sp-download is a CLI tool for simple document download which can be handy for admins, also is a library for adding download function to Node.js scripts and apps

**Comment by stephen-walsh** [comment]
Thanks for all you help!

I've tried the correct URL, (i pasted into a web browser and it downloaded fine) 
but when i used it in the above mentioned code it didn't download right, downloaded file size is 4kb, the actual file size is 11.3kb

My use case is to get a specific list of documents in Sharepoint , download and analysis them.
(Ideally download as a Stream.) 

The document i'm testing with is one that was made in Google Docs, and then uploaded to Sharepoint as a docx

**Comment by stephen-walsh** [comment]
this is the code im using

```
  this.spr.get(endpointUrl, {
      headers: requestHeadersPass,
      agent: this.util.isUrlHttps(endpointUrl) ? this.settings.agent : undefined
    })
      .then((response: any) => {
        if (this.settings.debugOutput) {
          console.log('\nHeaders:');
          console.log(JSON.stringify(response.headers, null, 2));
          console.log(response.statusCode, response.body);
        }
        res.status(response.statusCode);
        if(response.headers["content-type"] == "application/octet-stream") {
  
          const cpass = new Cpass();
          let context: IAuthOptions;
          context = require(path.resolve("./config/private.json"));
          (context as any).password = (context as any).password && cpass.decode((context as any).password);
          const download = new Download(context);
      
          let filePathToDownload: string = "https://<SITE>.sharepoint.com/sites/<COMPANY>/web/Shared Documents/test doc.docx"
          
          let saveToPath: string = '/Users/stephen/Desktop';
          
      
          download.downloadFile(filePathToDownload, saveToPath)
            .then(savedToPath => {
              console.log(`XXX has been downloaded to ${savedToPath}`);
            })
            .catch(error => {
              console.log(error);
            });
      
          res.end(response.body, 'binary');
        }
        else {
          res.json(response.body);
        }


```

**Comment by koltyakov** [comment]
Yeah, sp-resp-proxy is more a dev toolchain.

For your task, `sppull` or `sp-download` should suit better.
Both support streams ([1](https://github.com/koltyakov/sppull/blob/master/src/api/index.ts#L239), [2](https://github.com/koltyakov/sp-download/blob/master/src/api/Download.ts#L77)). `sp-request` doesn't support streams as it is based on request-promise. Streams can't be used in request-promise.
`sppull` switches to downloading as a stream if a file size is greater than 20 MB (I ended up with such value after observations of memory/speed comparison on large arrays of files of different sizes).
`sp-download` always uses download as a stream.

>downloaded file size is 4kb, the actual file size is 11.3kb

Something wrong in the middle, as I've never experienced such a behavior.
These tools are everywhere in our team developers' toolchains.
SPPull is on production tasks for syncing huge libs to external audit ECMs and tools.
sp-download is used for downloading from small Excels in BI/ETL tasks up to downloading huge video files.

> My use case is to get a specific list of documents in Sharepoint , download and analysis them.

How do you detect which files to download? How do you get this list of files?
`sppull` has multiple options for:
- download from a folder
- download a specific list of files
- recursive download
- "download" only folder structure
- download based on metadata filtering (CAML condition)

If you could provide more details, probably I can prepare a demo code sample for the use case.

Going to close this issue on this project. Please feel free to post an issue/question to the related project or in our [gitter](https://gitter.im/sharepoint-node/Lobby) chat room.

Have a good day!

**Comment by koltyakov** [comment]
Just seen your comment with the code after I posted the previous comment.
The part with sp-download looks valid. Please post an issue to its project if the situation with different file size continues appearing.

Also, could you please try, if in CLI mode file size is different?

```bash
npm install sp-download -g
```

then

```bash
sp-download --url="https://<SITE>.sharepoint.com/sites/<COMPANY>/web/Shared Documents/test doc.docx" --out="/Users/stephen/Desktop"
```
