### ISSUE TITLE
Usage with Search API

### ISSUE THREAD

**Issue by dafabulousteach** [koltyakov/sp-rest-proxy#40]
This is a question, than more of an issue, but can this library be used with the SP Search API? I find that the results are not populated in the response

**Comment by koltyakov** [comment]
Hey Kim,

Yes, it can definitely be used with REST API, as well as JSOM, SOAP, custom WCF and even static resources.
Search (`/_api/search`) is part of REST API.
Any details, what is wrong with the response? Do the results come back when executing the same request in a context of SharePoint page?

**Comment by dafabulousteach** [comment]
The error is on my end. A response comes back, but the response array is empty. My SP site utilizes a port number to retrieve data from the lists, but search is not configured to use the port number. Thanks for replying

**Comment by koltyakov** [comment]
Oh, if it's not proxy-related, closing the issue. Feel free to reopen in case of questions.
