### ISSUE TITLE
I get /_api/contextinfo 401 (Unauthorized) document upload

### ISSUE THREAD

**Issue by tobiashoeft** [koltyakov/sp-rest-proxy#43]
When i try upload a document to libary i get 401 

Here my code : OPTIONS http://XXXXXX/_api/contextinfo 401 (Unauthorized)

I use sp-pnp-js and your sp-rest-proxy for locally development.

   ```
  const siteUrl = "http://XXXXXXX/XXXXXXX/";
    this.web = new Web(siteUrl);
    if (file.size <= 10485760) {
      // small upload
      this.web
        .getFolderByServerRelativeUrl("/Shared%20Documents/")
        .files.add(file.name, file, true)
        .then(_ => Logger.write("done"));
    } else {
      // large upload
      this.web
        .getFolderByServerRelativeUrl("/Shared%20Documents/")
        .files.addChunked(
          file.name,
          file,
          data => {
            Logger.log({
              data: data,
              level: LogLevel.Verbose,
              message: "progress"
            });
          },
          true
        )
        .then(_ => Logger.write("done!"));
    }
  } 


```

```
"dependencies": {
    "@angular/animations": "^5.2.3",
    "@angular/common": "^5.2.3",
    "@angular/compiler": "^5.2.3",
    "@angular/core": "^5.2.3",
    "@angular/forms": "^5.2.3",
    "@angular/http": "^5.2.3",
    "@angular/platform-browser": "^5.2.3",
    "@angular/platform-browser-dynamic": "^5.2.3",
    "@angular/router": "^5.2.3",
    "@angularclass/hmr": "^2.1.3",
    "@ultimate/ngxerrors": "^1.4.0",
    "bevlis-spa-kaf-list": "0.0.31",
    "bootstrap": "^4.0.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.3",
    "cssnano": "^3.10.0",
    "font-awesome": "^4.7.0",
    "intl": "^1.2.5",
    "jquery": "^3.3.1",
    "ngx-bootstrap": "^2.0.2",
    "ngx-loading": "^1.0.14",
    "ngx-modal-dialog": "^1.1.1",
    "postcss": "^6.0.17",
    "rxjs": "^5.5.6",
    "sp-pnp-js": "^3.0.5",
    "weakmap": "0.0.6",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.8",
    "@angular/compiler-cli": "^5.2.3",
    "@angular/language-service": "^5.2.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~9.4.1",
    "codelyzer": "~4.1.0",
    "jasmine-core": "~3.0.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.1",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "sp-rest-proxy": "^2.5.4",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.7.1"
  }
```

**Comment by koltyakov** [comment]
Hi Tobias,

Could you try to increase `rawBodyLimitSize` in proxy settings?

```typescript
const RestProxy = require('sp-rest-proxy');

const settings = {
  configPath: './config/private.proxy.json',
  port: 8080,
  rawBodyLimitSize: '15MB' // Defalt is 2MB
};

const restProxy = new RestProxy(settings);
restProxy.serve();
```

For `files.addChunked`, I was reported with an issue on our current internal project.

@sergeisnitko, could you please recall how we ended up with upload feature this week? Did we just increase a size and decided not to upload large files in local mode?

Anyway, I'll take a look how to resolve `files.addChunked` case.

**Comment by tobiashoeft** [comment]
Hi Koltyakov, 

thix for fast reply to my issue.

I set it to 15mb like you're showing below.

Now i get this error : 




`
zone.js:1022 POST http://localhost:4200/_api/web/getFolderByServerRelativeUrl('/Freigegebene%20Dokumente/')/files/add(overwrite=true,url='RS_Monatssummen.pdf') 400 (Bad Request)
(anonymous) @ zone.js:1022
FetchClient.fetch @ fetchclient.js:10
retry @ httpclient.js:62
(anonymous) @ httpclient.js:89
ZoneAwarePromise @ zone.js:875
HttpClient.fetchRaw @ httpclient.js:81
(anonymous) @ httpclient.js:48
ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4745
ZoneDelegate.invoke @ zone.js:387
Zone.run @ zone.js:138
(anonymous) @ zone.js:858
ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:4736
ZoneDelegate.invokeTask @ zone.js:420
Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1517
globalZoneAwareCallback @ zone.js:1543
2logging.js:176 Message: Error making HttpClient request in queryable: [400] Bad Request Data: {"responseBody":"{\"odata.error\":{\"code\":\"-2147024809, System.ArgumentException\",\"message\":{\"lang\":\"de-DE\",\"value\":\"Der Wert liegt au\\u00dferhalb des erwarteten Bereichs.\"},\"innererror\":{\"message\":\"Der Wert liegt au\\u00dferhalb des erwarteten Bereichs.\",\"type\":\"System.ArgumentException\",\"stacktrace\":\"   bei Microsoft.SharePoint.SPWeb.GetWebRelativeUrlFromUrl(String strUrl, Boolean includeQueryString, Boolean canonicalizeUrl)\\r\\n   bei Microsoft.SharePoint.ServerStub.SPWebServerStub.GetFolderByServerRelativeUrl_MethodProxy(SPWeb target, ClientValueCollection xmlargs, ProxyContext proxyContext)\\r\\n   bei Microsoft.SharePoint.ServerStub.SPWebServerStub.InvokeMethod(Object target, String methodName, ClientValueCollection xmlargs, ProxyContext proxyContext, Boolean& isVoid)\\r\\n   bei Microsoft.SharePoint.Client.ServerStub.InvokeMethodWithMonitoredScope(Object target, String methodName, ClientValueCollection args, ProxyContext proxyContext, Boolean& isVoid)\\r\\n   bei Microsoft.SharePoint.Client.Rest.RestRequestProcessor.InvokeMethod(Boolean mainRequestPath, Object value, ServerStub serverProxy, EdmParserNode node, Boolean resourceEndpoint, MethodInformation methodInfo, Boolean isExtensionMethod, Boolean isIndexerMethod, Boolean useArgumentNode)\\r\\n   bei Microsoft.SharePoint.Client.Rest.RestRequestProcessor.GetObjectFromPathMember(Boolean mainRequestPath, String path, Object value, EdmParserNode node, Boolean resourceEndpoint, MethodInformation& methodInfo)\\r\\n   bei Microsoft.SharePoint.Client.Rest.RestRequestProcessor.GetObjectFromPath(Boolean mainRequestPath, String path, String pathForErrorMessage)\\r\\n   bei Microsoft.SharePoint.Client.Rest.RestRequestProcessor.Process()\\r\\n   bei Microsoft.SharePoint.Client.Rest.RestRequestProcessor.ProcessRequest()\\r\\n   bei Microsoft.SharePoint.Client.Rest.RestService.ProcessQuery(ClientServiceHost serviceHost, Stream inputStream, IList`1 pendingDisposableContainer)\"}}}","responseHeaders":{}}`

**Comment by koltyakov** [comment]
Are you dealing with a root web?
Are you using Webpack Dev Server "proxying to proxy"?

I have some concerns that this URL is valid:

`http://localhost:4200/_api/web/getFolderByServerRelativeUrl('/Freigegebene%20Dokumente/')/files/add(overwrite=true,url='RS_Monatssummen.pdf')`

We always configure local requests corresponding to the real SP path structure.
E.g. having a dev web at "http://sp.something.com/sites/site/web" it's always `http://localhost:4200/sites/site/web/_api` in a local workbench. Yeah, proxy turns `http://localhost:4200/_api` to `http://localhost:4200/sites/site/web/_api` automatically, but it's better getting a correct local URL.

`getFolderByServerRelativeUrl('/Freigegebene%20Dokumente/')` - no questions, if it's a root web, but if not, this part is incorrect and should be `getFolderByServerRelativeUrl('/sites/site/web/Freigegebene%20Dokumente/')`.

Btw, there is a helper for getting web context:

```typescript
import { loadPageContext } from 'sp-rest-proxy/dist/utils/env';
import { Web } from 'sp-pnp-js';

loadPageContext().then(_ => {
  const web = new Web(_spPageContextInfo.webAbsoluteUrl);
  // We wrap our apps with such bootstrap so the app works the same in a local workbench 
  // and later on deployed to SharePoint
}).catch(log);
```

Right now I'm checking on a prod app (React, Webpack Dev Server, sp-rest-proxy v. 2.5.4, sp-pnp-js ) example and the same upload story:

![image](https://user-images.githubusercontent.com/7816483/36339933-e554446c-13e0-11e8-8915-61581581708c.png)

and it works for me:

![image](https://user-images.githubusercontent.com/7816483/36339940-18b7dcec-13e1-11e8-8224-3716d0575e54.png)

With large files, it fails (checking if it possible to fix).

**Comment by koltyakov** [comment]
UPD: Hm... I was on sp-pnp-js 3.0.4, just updated to 3.0.5. And something went wrong.

**Comment by koltyakov** [comment]
Found a bug in sp-pnp-js (going to apply a PR there). =)
Added support for chunk upload to sp-rest-proxy, going to publish the updates after fixing sp-pnp-js's methods.
Btw, addChunked API works in SPO only.

**Comment by koltyakov** [comment]
So I was managed to make addChunked work.

Requirements:

- SPO
- `rawBodyLimitSize` should be greater than file size to load
- OData mode should be `minimalmedata` or `nometadata`, with `verbose` it fails due a bug in PnP which I'm going to fix sooner

Also, there is another bug in addChunked response. The data prop does not return file's metadata, but a File object. Gonna fix it too.

**Comment by tobiashoeft** [comment]
Hey thx for reply! Thx !!!!

Yeah exactly! That's why it don't work.

Thx :D !

You're awesome!

**Comment by koltyakov** [comment]
Thanks! Closing the issue.
