### ISSUE TITLE
private.json clientSecret gets overwritten

### ISSUE THREAD

**Issue by MiliusCZ** [koltyakov/sp-rest-proxy#45]
I'm using sp-rest-proxy with SharePoint Online, OnlineAddinCredentials authentication strategy. I have clientId and clientSecret in private.json
With version 2.5.3, it worked nicely
After upgrade to 2.5.5. each time I run the proxy (using node myPath/server.js), the clientSecret in private.json get's overwritten by random string (which is 2,5 times longer that the secret).
After downgrading back to 2.5.3 the issue stays until I remove node_modules and yarn.lock file and run yarn again

**Comment by koltyakov** [comment]
Hi @MiliusCZ,

It's not a random string, but a hashed version of client secret, which can be decoded only on the machine where it was encrypted.

This behavior is configurable you can force passwords and secrets to be in raw form by `encryptPassword` equals `false`:

```typescript
(new RestProxy({
  configPath: './config/private.json',
  authConfigSettings: {
    encryptPassword: false
  }
})).serve();
```

**Comment by MiliusCZ** [comment]
Great.. thanks for answering my question!
