### ISSUE TITLE
Electron form no longer working for On-Demand auth

### ISSUE THREAD

**Issue by esandeep** [koltyakov/sp-rest-proxy#47]
Something changed in last 4 month and now when I select on-demand auth option, the electron form is unable to perform authentication. I have been unable to debug the form and get more info on the issue. 
I am using it for SharePoint online where PingID is being used for id federation. It was working perfectly fine till September last year. Not very sure when I used last though.

**Comment by koltyakov** [comment]
Hey @esandeep,

Can you check if [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth) (the library which used for authentication) works for you and post some details as a connected issue?
