### ISSUE TITLE
jetNexus NTLM

### ISSUE THREAD

**Issue by dinogit** [koltyakov/sp-rest-proxy#48]
Hi @koltyakov 

Thank you for this amazing plugin. It saved me lots of hours working, instead of constantly deploying and watching what does not work now. Anyway, company had previously been using TMG, and now we switched to jetNexus that is using NTLM, so when I type my credentials and test API I get: 

![error_ntlm](https://user-images.githubusercontent.com/1814086/38040438-d12dc59c-32af-11e8-860f-c8817abeec4c.png)

Tried with authCheck like you explained last time, but I get same error.

**Comment by koltyakov** [comment]
Hi @dinogit,

Thanks for using the library!
 
I have a guess that NTML v2 might be used which is not supported with `node-sp-auth` (the library making the magic of authentication). Could you check the windows registry key (on the SharePoint server(s))? https://technet.microsoft.com/en-us/library/cc960646.aspx

What is the exact error message when using [this](https://github.com/koltyakov/sp-rest-proxy/issues/30#issuecomment-336253564) approach?

Did you try reconfiguring connection settings from scratch? If it still uses TMG strategy auth won't even try NTML.

**Comment by dinogit** [comment]
Hi @koltyakov,

guys from Network Department ware able to fix this on their part, so it's working as before.

Thanks for quick response.
