### ISSUE TITLE
Merge request support to update items

### ISSUE THREAD

**Issue by hammadfauz** [koltyakov/sp-rest-proxy#54]
To update an item, via rest, need to do a `MERGE` request or a `POST` request with `X-HTTP-Method` set to `MERGE`. Also need to send `If-Match` header to ensure the right version is being merged.

Response for such request does not contain `Content-Type`, which crashes the proxy.

**Comment by koltyakov** [comment]
Hey @hammadfauz, 

Could you please provide some code samples which fail for you with proxy but work on SP pages?
We use proxy in many dev scenarios with almost any combination of requests and never experience any issues with items update.

**Comment by hammadfauz** [comment]
@koltyakov I think you guys are using SOAP endpoints more. I prefer to communicate using json, so I use REST.

My scenario is SharePoint 2010 REST services (mostly via `http://server/site/_vti_bin/ListData.svc` )

For the above issue, in order to update a list item, I needed to send request as below:
```
fetch('_vti_bin/ListData.svc/ListName(1)',{
  credentials : 'include',
  method : 'post',
  headers : {
    'Accept' : 'application/json;odata=verbose',
    'X-HTTP-Method' : 'MERGE',
    'If-Match' : '*',
    'Content-Type' : 'application/json'
  },
  body : JSON.stringify({ changed_property : 'changed_value' })
})
```
I think all `ListData.svc` requests go to `genericPost` and `genericGet` routers as fallback.

Might need to create a specific router for these if there are a lot of changes needed, IMO.

Also, thanks for the awesome work on this!

**Comment by koltyakov** [comment]
Hi @hammadfauz,

Sorry for such a long delay. It happened so that I missed completely that there was the comment from you and never come back to the issue until recently.

Could you please check the 2.7.0 version, the legacy 2010 REST support has been added. 

Going to close the issue.
