### ISSUE TITLE
sp-pnp-js getAll method fails with sp-rest-proxy 2.5.9

### ISSUE THREAD

**Issue by vpsrihari** [koltyakov/sp-rest-proxy#56]
Hi Koltyakov,

Thanks for issuing a fix for the comment I posted yesterday on sp-pnp-js thread [here](https://github.com/SharePoint/PnP-JS-Core/issues/689)

I updated my proxy server and retried the getAll method. It worked fine for smaller lists but failed for larger lists (above 5000 items). Could you please look into this. Thank you. 

Failed to load {{direct url to site here}}: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1234' is therefore not allowed access. The response had HTTP status code 401. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by vpsrihari** [comment]
I think the request is failing if the returned results is more than 1 page. 

I have two queries that return 245 and 5200 results. When I run getAll() it works fine for first query and fails for the second. But when I run getAll(100), it fails for both. So, the issue is not with the size of list but with the length of results. Hope this helps identify the issue.

**Comment by koltyakov** [comment]
I guess I know. I tried with non-verbose odata mode before. What you described still happens for verbose. Np, will amend this.

**Comment by koltyakov** [comment]
Nice! Thanks for using the libs! Closing this issue as fixed.
