### ISSUE TITLE
SP2013- On prem- NTLM- Undefined issue

### ISSUE THREAD

**Issue by esandeep** [koltyakov/sp-rest-proxy#58]
I am getting this from a 2013 on-prem env. 
{
  "readyState": 4,
  "responseText": "401 - undefined",
  "status": 401,
  "statusText": "Unauthorized"
}
On-deman normally has worked for me other places but here with on-demand, I get this:
{
  "readyState": 4,
  "responseText": "Cookie array is empty",
  "status": 500,
  "statusText": "Internal Server Error"
}

**Comment by koltyakov** [comment]
Hi @esandeep,

On-Demand auth is designed for different form-based auths.
With NTML, On-Demand can't be used.

Can it be that NTLMv2 is configured in your environment without fallback to NTLMv1?
If so, can you try installing `npm install --save-dev node-sp-auth@ntlm2`?

**Comment by esandeep** [comment]
Wow, that worked. Thanks a bunch!!!

**Comment by koltyakov** [comment]
Cool! For the info, the new version of node-sp-auth with NTMLv2 support will be added as `sp-rest-proxy` dependency right after it will be published with @latest tag. So, for NTMLv2, please temporary use this `node-sp-auth@ntlm2` dependency installed strictly.
