### ISSUE TITLE
Kerberose Auth

### ISSUE THREAD

**Issue by esandeep** [koltyakov/sp-rest-proxy#60]
I am trying to use this proxy with an On-Prem 2013 installation that uses Kerberos and tokens are created using IBM Datapower. Getting below error:
{
  "readyState": 4,
  "responseText": "Invalid message signature: Negotiate",
  "status": 500,
  "statusText": "Internal Server Error"
}

Is it not supported or am I doing something wrong?

**Comment by esandeep** [comment]
I see another post where you responded the NTLMv2/Kerberos not supported. However, this works with NTLM v2 with the node-sp-auth@ntlm2 package. Therefore I am hoping that there may be a solution to support Kerberos too.

**Comment by koltyakov** [comment]
Hi @esandeep,

NTLMv2 support was recently added. 

However, Kerberos auth is not supported.

**Comment by esandeep** [comment]
Thanks for the quick response. Is that on roadmap?
