### ISSUE TITLE
Bad Request - Invalid Verb

### ISSUE THREAD

**Issue by Korigoth** [koltyakov/sp-rest-proxy#62]
We are experiencing an issue sporadicly and getting Bad Request - Invalid Verb from the proxy.

We were testing with this method to make it pretty simple.

```
import { sp, List } from '@pnp/sp';

const flow = (list: List) => {
  list.items.add({ Title: new Date().toISOString() })
    .then(({ data }) => {
      setTimeout(() => {
        list.items.getById(data.Id).delete()
          .then(() => flow(list))
          .catch(console.log);
      }, 1000 * 30); // creating and deleting an item per 30 sec until fail 
    });
};

flow(sp.web.lists.getByTitle('My List'));
```

It took 9h for it to fail.

Here is the request

![pnp-call-fail](https://user-images.githubusercontent.com/10915055/44464057-b0615f80-a5e7-11e8-8d5f-e4e76ec58950.png)

Here is the response

`"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>\r\n<BODY><h2>Bad Request - Invalid Verb</h2>\r\n<hr><p>HTTP Error 400. The request verb is invalid.</p>\r\n</BODY></HTML>\r\n"`

We are using UserCredentials strategy and SharePoint Online for dev.
I will test it again tonight to see if it take around the same time to fail and post it here.

If any more test or informations is required, just ask me, i will do my best to test!

**Comment by Korigoth** [comment]
I've done an other test this morning and it didn't take too long before the error's happened.

It's again on the DELETE verb, everything is the same exept the ID of the item.

**Comment by koltyakov** [comment]
Intermittent issues are tremendously hard to troubleshoot. On a long-running test session, I got something similar. It was on another method. I still quite unsure what it might be.

**Comment by Korigoth** [comment]
ok, thanks for your time! It's not a prod problem so it's still ok, but sometime we break some entities and lose time to fix those entities ;)

**Comment by koltyakov** [comment]
@Korigoth,

Can you help me with debug with the following approach using Fiddler:

1\. Add these lines before `new RestProxy(settings).serve();`:

```javascript
process.env.http_proxy = 'http://127.0.0.1:8888';
process.env.https_proxy = 'http://127.0.0.1:8888';
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
```

This should enable traffic through Fiddler.

2\. Execute long-running code.
3\. Be sure that requests are captured in Fiddler. Filter for the process can be handy to track only requests to SharePoint API.
4\. Wait until the error.
5\. Check if the response from SharePoint was bypassed and proxy just returned what came from SP, etc.

**Comment by Korigoth** [comment]
Ok, i will try to take some minutes before leaving to test it.
So i need to download fidler ?

or do i see it in cmd console ?

**Comment by Korigoth** [comment]
@koltyakov 

Here i got an error similar and it seems's the proxy couldn't connect to our sharepoint online site

[Fiddler] The connection to 'ccauxtransports.sharepoint.com' failed. 
Error: TimedOut (0x274c). 
System.Net.Sockets.SocketException Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu 13.107.136.9:443 

![header-no-tunnel](https://user-images.githubusercontent.com/10915055/44791296-4c064900-ab6f-11e8-9d61-5344c8deed50.png)

![response-no-tunnel](https://user-images.githubusercontent.com/10915055/44791306-4f99d000-ab6f-11e8-9e38-81fc7ff63a92.png)

Sorry, my computer is in french so the errors are displaying in french too :)
So it's a timeout error for this one, i will wait to get the real error of socket to show it here!

I know that timeout error is not the proxy fault ;)
We should just wait for the socket error to happen again to see if it's sharepoint online fault again!

**Comment by koltyakov** [comment]
I would have added some retry logic, but not sure if it's correct as the main goal is to behave as close as if it was an app talking to SharePoint. Any enrichments might end up with a code working in proxy mode, but failing after deployment to SharePoint which is obviously not a good thing.

**Comment by LBoyle** [comment]
I've had this issue on POST, the same error, using pnp/sp. 
I'm trying to update the list that underlies a document library, my browser reports a POST, the error says I used a GET. 
This happens to one of numerous parallel requests all doing the same thing in a Promise.all, all succeed except one which produces this error. 

We used fetch initially making our own urls, and never saw this, then using pnp/sp with the proxy it suddenly shows up a few days ago. 

Not much of value to offer, just letting you know. 

P.S. If it is the proxy, great news for me because it won't happen in production.

**Comment by koltyakov** [comment]
Hi @LBoyle,

Is it something you can reproduce with a guaranty or intermittent one?
If reproducible, can you try on SP page will it end up with no errors or the same?

The proxy doesn't convert methods, I can't imagine a case when POST sent to the proxy ended up with GET to SP API.

**Comment by LBoyle** [comment]
It's intermittent, I wasn't able to produce it today, I was able yesterday, and my manager was on his machine. I'm kind of stumped as well. 
Like you say, no errors in the SP page, so it's not a blocker. 

If I find something useful, I'll post it here.

**Comment by Korigoth** [comment]
@koltyakov Same here, we are in production build for more than a month and we got no problem with pnp/js. We did have this error that i've created in the past but it seem's ok now. We switched from SP-Online to SP-OnPrem, so i don't know if it really change something?

**Comment by tusharprithviraj** [comment]
@koltyakov 
 I used your project just to test sp-rest-proxy 
i passed my site URL and credentials SAML, but getting the below errors .
![image](https://user-images.githubusercontent.com/46158835/50442530-52da7800-0925-11e9-80ea-f61e3a219b9d.png)
 I tried putting the entire url and got the below error, please suggest.I am trying to connect to sharepoint online.
![image](https://user-images.githubusercontent.com/46158835/50442656-d4320a80-0925-11e9-92a6-1d0570a6a134.png)
