### ISSUE TITLE
Proxy Connection over Network

### ISSUE THREAD

**Issue by KI-G** [koltyakov/sp-rest-proxy#65]
Hi, Is it possible to connect to the proxy over network? I mean it's possible to connect to http://localhost:8080, but not to http://197.0.0.x:8080. Seems like the is no binding to the current IP. This would be extremely helpful for Mobile debugging in a WiFi Network .... Or did I miss something in the settings?

BTW: I'm using your proxy with vue-cli 3 and it's really a game changer for me. Thanks very much, Really appreciate your work!

**Comment by koltyakov** [comment]
Hi Guido, thank you for the question and good words!
Yes, it's possible to configure/redefine defaults. By default, proxy listens on `localhost` and port `8080`.
Host and port can be reconfigured using environment variables: HOSTNAME and PORT. Or these guys can be provided strictly while initiation of the proxy in code:

```typescript
new RestProxy({
  hostname: '10.42.7.50',
  port: 3777
}).serve();
```

So, for instance, this `10.42.7.50` was an IP in the internal network at home, then I configured port forwarding on a router and was able to consume API from within my network at work via domain name registered to public IP. For a LAN scenario, it's even easier.

**Comment by KI-G** [comment]
Perfect, thank you very much! Works like a charm. App Development with Hot-Reloading and live Office365 Data on a mobile phone.... sharepoint dev has changed quite a bit ^^

**Comment by koltyakov** [comment]
Thank you for using the lib!
