### ISSUE TITLE
How to authenticate with smart card on demand

### ISSUE THREAD

**Issue by spevilgenius** [koltyakov/sp-rest-proxy#72]
I am in an environment where I use a smart card to authenticate. I selected on demand but get a bad request on any query when it goes to execute. Is there another setting to adjust to support that scenario??

**Comment by koltyakov** [comment]
Hi @spevilgenius,
 
Do you have Electron installed globally? It is required for On-Demand flow.

sp-rest-proxy uses [node-sp-auth](https://github.com/s-kainet/node-sp-auth) library for authentication. So it's better creating auth-related issues/questions in node-sp-auth's repo.

**Comment by spevilgenius** [comment]
Yes, electron is installed globally. I will see about posting to that repo instead. Thanks!!

**Comment by koltyakov** [comment]
Btw, [this project](https://github.com/koltyakov/node-sp-auth-troubleshoot) can simplify things for generic auth troubleshooting.

**Comment by koltyakov** [comment]
The version of Electron can also make sense as Electron changed CLI arguments format after 2nd version. We've aligned the format with the latest Electron. I'd recommend targeting On-Demand to a predictable environment, e.g. OOTB SPO and check if it works.

**Comment by koltyakov** [comment]
Let me close this one as related to auth library.
