### ISSUE TITLE
Empty Post causing 400 Error Bad Request 

### ISSUE THREAD

**Issue by senseiweb** [koltyakov/sp-rest-proxy#73]
First awesome plugin -- save me so many headaches. Releases 2.8.1 thru 2.8.4 seems to have a bug that causes a 400 error when sending an empty post request to the SP Online environment. In particular, using the sp.executeQueryAsync generating a post request for contextinfo will cause an error when attempting to make the request.

**Comment by koltyakov** [comment]
Thanks, @senseiweb,

Can you provide a code sample which ends up with an error so I can add it to test cases?

**Comment by koltyakov** [comment]
I've figured out. Patched in v2.8.8
