### ISSUE TITLE
I can not load _spPageContextInfo to my React components

### ISSUE THREAD

**Issue by Shmata** [koltyakov/sp-rest-proxy#74]
Hi , 
I have a question , I can not load **_spPageContextInfo**  In my react components , 
![load](https://user-images.githubusercontent.com/2398297/56265996-5b3b0680-6100-11e9-8555-b1cea14084b2.jpg)
I will thankful if you help me . 
![Untitled](https://user-images.githubusercontent.com/2398297/56266646-fa143280-6101-11e9-96de-70114d7819d5.png)

**Comment by Shmata** [comment]
Dear @koltyakov ,

I tried
 `const Context = typeof _spPageContextInfo !=="undefined" ? _spPageContextInfo : {}; 

export default Context;`
 then in SharepointServices class I called **Context**  but It is also undefined . (below screenshot )
![2](https://user-images.githubusercontent.com/2398297/56283509-38701880-6127-11e9-9ba0-f1fd2a0a4978.png)

[Here ](https://github.com/Shmata/MyTempProj) is my public repository , 
Thank you very much for your help.

**Comment by koltyakov** [comment]
So as I said, validations rules:

![image](https://user-images.githubusercontent.com/7816483/56284627-b29b9f80-611d-11e9-9313-4e903a5fbe05.png)

However, with your current `src\services\Context.js` implementation chances for the code to work are low, it may always end up with an empty object.

I still recommend using it this way:

```typescript
loadPageContext().then(async _spPageContextInfo => {
 // ...
});
```

**Comment by Shmata** [comment]
Dear @koltyakov,

I will follow your guides and update my project , then I’ll update this topic and give you that result.

**Comment by Shmata** [comment]
Dear @koltyakov , 
It works fine , Indeed you deserve to be a MVP. 
Many thanks.

**Comment by koltyakov** [comment]
Glad you figured out, cheers!
