### ISSUE TITLE
Custom svc service return 403 Forbidden

### ISSUE THREAD

**Issue by dyagilevart** [koltyakov/sp-rest-proxy#75]
Post requests to my svc service are executed with POST (generic): without X-RequestDigest.

My full link to POST method is:
http://devshp3/_vti_bin/CmxProblemRegistry.svc/AddComment

Can you add X-RequestDigest for such requests?

I tried to fix it myself, but I'm afraid that my decision is temporary
https://github.com/dyagilevart/sp-rest-proxy/commit/62818390ef9d48ec94a3be8a9ab00a7c9377e695#diff-dcf26db2a37aeae4da081788ebce549bR46

Thank you

**Comment by koltyakov** [comment]
Hi @dyagilevart,

Thanks for using the library. I'll take a look. Adding digest to generic POST should not be an issue.
ETA: Tomorrow. Will let you posted.

**Comment by koltyakov** [comment]
Could you try to check ver. 2.8.7? Just published the update.
Added digest for the generic POST. However, implemented it slightly bit different as not only `/_vti_bin` are routed to generic POST.

**Comment by koltyakov** [comment]
Cool, thanks!
