### ISSUE TITLE
Getting issue while using Add-in credentials SharePoint Online

### ISSUE THREAD

**Issue by siva111** [koltyakov/sp-rest-proxy#80]
Hi ,
Thanks for this wonderful work,
Am trying to connect SharePoint Online from SP Rest Proxy with Add-in credentials but getting following error
{
  "readyState": 4,
  "responseText": "Cannot read property 'replace' of undefined",
  "status": 400,
  "statusText": "Bad Request"
}

While i connect same site with Username password it works fine.

Can you please guide me if i need to do any more configuration to get it work with Add-in credentials.

Note: I have tried in 2 tenant site collections , result is same.

Thanks in Advance.

Regards,
Siva

**Comment by koltyakov** [comment]
Hi @siva111,

Thanks for using the library and reporting the issue! Please check the updated v2.8.10.
There was some update to auth/conf libraries which cause a temporary issue with resolving AddIn Only strategy, it ended up with SAML.
Also, check that in `./config/private.json` there is no `"online"` property.

**Comment by siva111** [comment]
Hi Andrew,
Thanks for the speedy response.
I tried using v2.8.10 and now am getting following error.
{
  "readyState": 4,
  "responseText": "Error: unable to get local issuer certificate",
  "status": 400,
  "statusText": "Bad Request"
}
I am getting same error while i tried node-sp-auth . 
Any clues on this error.

Thanks in advance.

**Comment by koltyakov** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/7816483/60247757-e9362900-98c9-11e9-98bb-3182915d4b1a.png)

Can you verify clientId and clientSecret are correct?

No other clues.
If nothing helps and you'll be sure it's not on your end please post an issue in node-sp-auth repo.

**Comment by siva111** [comment]
Hi @koltyakov ,

Seems to be some certificate &  proxy  issue , now am able to get the data.
Since it is a dev environment i made Node to ignore NodeTLS certificate. ( SET NODE_TLS_REJECT_UNAUTHORIZED=0)
Thanks a lot for your help. Please close the issue.
