### ISSUE TITLE
SharePoint returns other json than proxy

### ISSUE THREAD

**Issue by svdoever** [koltyakov/sp-rest-proxy#9]
I have the following code:

```
<!DOCTYPE html>
<html>
<head>
    <title>Show title using REST</title>
    <meta name="viewport" content="width=device-width, maximum-scale=1, user-scalable=no" />

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.0.5/es6-promise.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.1/fetch.min.js"></script>
</head>
<body>
    <h1 id="title">Loading...</h1>
    <script>
        fetch(new Request('/_api/web/title', { credentials: 'include', headers: new Headers({"Accept": "application/json"}) }))
        .then(function(response) {
            return response.json();
        })
        .then(function(json) {
            title = json.value;
            var titleElement = document.getElementById('title');
            titleElement.innerHTML = title;
        })
        .catch(function(ex) {
            console.log('Error:', ex)
        });
    </script>
</body>
</html>
```

If I execute this through the proxy as `index.html` I get the following JSON in the body:

```
{"d":{"Title":"apps"}}
```

If I upload the page to a SharePoint document library as `index.aspx` I get the following JSON in the body:

```
{"odata.metadata":"https://macaw-my.sharepoint.com/personal/serge_macaw_nl/apps/_api/$metadata#Edm.String","value":"apps"}
```

Is there a way to get the data in the same format so I can develop through the proxy and switch to real SharePoint?

I found the post https://blogs.office.com/2014/08/13/json-light-support-rest-sharepoint-api-released/ for configuring the amount of meta-data, but the settings:

```
“accept: application/json; odata=verbose”
“accept: application/json; odata=minimalmetadata”
“accept: application/json; odata=nometadata”
```

don't help in getting output in the same format.

**Comment by svdoever** [comment]
The post http://sharepoint.stackexchange.com/questions/183984/rest-call-d-results-vs-value shed some light. if I specify “accept: application/json; odata=verbose” I get the same format, but I can't get the proxy to return is the other formats like “accept: application/json; odata=nometadata”.

**Comment by svdoever** [comment]
Damn, still not exactly the the same! I now use:

```
fetch(new Request("http://localhost:8081/_api/web/title", 
                { 
                    credentials: 'include', 
                    headers: new Headers({"Accept": "application/json; odata=verbose"}) 
                }))
```

The proxy returns:

![screen shot 2016-12-01 at 21 47 02](https://cloud.githubusercontent.com/assets/246842/20811962/0e260bc4-b810-11e6-9612-9b74917f1e0e.png)


and SharePoint returns:

![screen shot 2016-12-01 at 21 47 23](https://cloud.githubusercontent.com/assets/246842/20811911/dd98d928-b80f-11e6-87a4-f18e98a42abd.png)

**Comment by koltyakov** [comment]
Hi Serge,

There is such a possibility that headers are different.
I've tweaked headers passby a bit and managed to get the following results:

![img](http://koltyakov.ru/images/ProxyOdataVerbouseIssue9.jpg)

"application/json; **odata=verbose**" - has to be inscluded to es6-promise request I believe.

Could you please check if it works for your scenarios?

**Comment by svdoever** [comment]
This would be great! I will check it this weekend.

Regards,
Serge



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Andrew Koltyakov <notifications@github.com>
Datum: 02-12-16 13:52 (GMT+01:00)
Aan: koltyakov/sp-rest-proxy <sp-rest-proxy@noreply.github.com>
Cc: Serge van den Oever <Serge.van.den.Oever@macaw.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [koltyakov/sp-rest-proxy] SharePoint returns other json than proxy (#9)


Hi Serge,

There is such a possibility that headers are different.
I've tweaked headers passby a bit and managed to get the following results:

[img]<https://camo.githubusercontent.com/c49c91f33961d75ffc570f4e69de6e2f325670c2/687474703a2f2f6b6f6c7479616b6f762e72752f696d616765732f50726f78794f64617461566572626f7573654973737565392e6a7067>

"application/json; odata=verbose" - has to be inscluded to es6-promise request I believe.

Could you please check if it works for your scenarios?

-

**Comment by svdoever** [comment]
Works great, now the same result as executed directly on SharePoint! But...

The api test page now gives error:

```
Unhandled rejection RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:566:10)
    at ServerResponse.send (/Users/Serge/projects/serge/sharepoint-progressive-web-apps/ShowTitleProgressiveWebApp/node_modules/express/lib/response.js:205:10)
    at ServerResponse.json (/Users/Serge/projects/serge/sharepoint-progressive-web-apps/ShowTitleProgressiveWebApp/node_modules/express/lib/response.js:250:15)
    at /Users/Serge/projects/serge/sharepoint-progressive-web-apps/ShowTitleProgressiveWebApp/node_modules/sp-rest-proxy/src/index.js:166:21
    at tryCatcher (/Users/Serge/projects/serge/sharepoint-progressive-web-apps/ShowTitleProgressiveWebApp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Serge/projects/serge/sharepoint-progressive-web-apps/ShowTitleProgressiveWebApp/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/Serge/projects/serge/sharepoint-progressive-web-apps/ShowTitleProgressiveWebApp/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/Serge/projects/serge/sharepoint-progressive-web-apps/ShowTitleProgressiveWebApp/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/Serge/projects/serge/sharepoint-progressive-web-apps/ShowTitleProgressiveWebApp/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/Serge/projects/serge/sharepoint-progressive-web-apps/ShowTitleProgressiveWebApp/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/Serge/projects/serge/sharepoint-progressive-web-apps/ShowTitleProgressiveWebApp/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/Serge/projects/serge/sharepoint-progressive-web-apps/ShowTitleProgressiveWebApp/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

Is probably still looking to the original result set...

**Comment by svdoever** [comment]
By the way: using sp-rest-proxy in my "SPA Series" blog posts...

**Comment by koltyakov** [comment]
Do you mean that the error is faced then you try a request on default index.html (SharePoint REST Proxy Example) page?
What particular request causes the issue? I've tried a couple of basic get calls and they worked. 

> "SPA Series" blog posts...
Oh, it was interesting to know about your blog. Checking it out, nice posts.

**Comment by svdoever** [comment]
I'm requesting /_api/web/title.
I rolled back to 1.1.5 and it was working, back to 1.1.6 and same error as above.

**Comment by koltyakov** [comment]
Hi Serge,

I was able to reproduce express issue message you have been facing. In my case it was wrong password hash (appeared after some experiments with Docker) to cause very similar behavior. And then I realized that there was an issue with rising real exception message.

A set of changes has been applied to the code.
Can you try the latest version (1.1.9, yep, there were some hassles that made me skip some versions)?

**Comment by svdoever** [comment]
@koltyakov it works like a breeze! Thank you so much, you are a hero!!

**Comment by ismet** [comment]
Hi,

I am having the same situation. I am developing an app using sp-rest-proxy on localhost. When I deploy it to SharePoint on-premise server, the api calls are not working since the returned data have different formats. I didn't get how you guys solve it. Btw, I'm using sp-pnp-js library for REST operations.

**Comment by koltyakov** [comment]
Hi @ismet,

Can you please provide some samples of the responses diff.
It'll be easier to figure out with it. Thanks!

**Comment by ismet** [comment]
Hi @koltyakov,

I use **/_api/web/title** for the samples. Here are the results:

1. Without sp-rest-proxy (http://intranet.spdev.com) 
```
{
    "value": "Welcome Site"
}
```

2. With sp-rest-proxy (http://localhost:8383)
```
{
    "d": {
        "Title": "Welcome Site"
    }
}
```

I get same results both in sending manual requests and using axios rest client.

**Comment by koltyakov** [comment]
Weird, I've never seen PnP-JS-Core returned such a format.
Quick test I've tried:

```javascript
$pnp.setup({
    headers: {
        'Accept': 'application/json; odata=verbose'
    }
});
$pnp.sp.web.select('Title').get().then(console.log);
```

On a proxy page and on a web page results format is identical:

```json
{
  "__metadata": {
    "id": "http://[...]/_api/Web",
    "uri": "http://[...]/_api/Web",
    "type": "SP.Web"
  },
  "Title": "Web Site Title"
}
```

**Comment by ismet** [comment]
You are right.. For me, the problem is not PnP-JS-Core but sp-rest-proxy.. 

It seems, sp-rest-proxy uses odata=verbose. But SharePoint uses odata=minimalmetadata in default.

Wouldn't it be better if sp-rest-proxy provides odata=minimalmetadata response instead of odata=verbose, so we don't have to setup additional headers for custom REST operations and deal with "d" objects?

**Comment by koltyakov** [comment]
I'll think about the bypassing odata mode.
You're right that a verbose mode is used in the proxy.

**Comment by koltyakov** [comment]
Created a separate issue for the latest comments https://github.com/koltyakov/sp-rest-proxy/issues/16 with OData modes.
