### ISSUE TITLE
Port issue

### ISSUE THREAD

**Issue by hasankoroglu** [koltyakov/sp-rest-proxy#91]
Hi dear contributers,

When i have tried the tool, i configured the server.js file. i defined the port as 8080 as the your readme file described. But when i start my react project it gives an error like:

> Proxy error: Could not proxy request /_api/web/GetFolderByServerRelativeUrl('/SitePages')/Files from localhost:3000 to http://localhost:8081/.
> See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

But if i change the port as 8081 it works.

Am i doing something wrong?

**Comment by koltyakov** [comment]
There are 2 approaches. The first one is routing client-side app requests to proxy's endpoint. And configuring local dev server to bypass API calls. The second one is in preference if the local dev server supports API proxy. There is an even [better way](https://github.com/koltyakov/sp-rest-proxy#webpack-dev-server) when Webpack Dev Server (which is mostly used for local dev serve) is not hidden in scaffolded project.

Ports should be aligned and no other web server should run on the same port at the same time.

I assume that you use CRA, and in its config (maybe following [this article](https://www.linkedin.com/pulse/getting-started-react-local-development-sharepoint-andrew-koltyakov/)) 8081 is set but in sp-rest-proxy 8080.
