### ISSUE TITLE
About loadPageContext

### ISSUE THREAD

**Issue by hasankoroglu** [koltyakov/sp-rest-proxy#92]
Hi @koltyakov,

As you suggested, i'm trying to use loadPageContext. My app runs on localhost:3000 and sp-rest-proxy runs on 8080 port. when i run my app, loadPageContext function tries to get data from localhost:3000/api/web... And it gives 404 error. What am i doing wrong? My public code is here: https://github.com/hasankoroglu/sp-pnp-js Sorry for bothering you with this simple issue :(

**Comment by koltyakov** [comment]
You're calling `loadPageContext();` without waiting when it is resolved.
Should be thenable logic or awaiting.
After, it's a good thing to check what's in `_spPageContextInfo.webAbsoluteUrl` property.

**Comment by hasankoroglu** [comment]
I think, i could not explain my problem clearly :( when i call the loadPageContext function, it is sending the request to the localhost:3000 (CRA dev server), but sp-rest-proxy runs on localhost:8080.

**Comment by koltyakov** [comment]
Do you have `"proxy": "http://localhost:8080",` in package.json? [Details](https://create-react-app.dev/docs/proxying-api-requests-in-development/). CRA proxies to the proxy, sp-rest-proxy adds auth and proxies to SharePoint. And too many `proxy` words in that sentence. :D

**Comment by hasankoroglu** [comment]
Thankx, thanx and thanx again. It's all about my missing information and missing learning :(
