### ISSUE TITLE
Error: Registry editing has been disabled by your administrator

### ISSUE THREAD

**Issue by tarundhillon** [koltyakov/sp-rest-proxy#93]
I am trying to use this proxy to setup a dev environment at client site which has very restrictive access policies. While running the server I get the below error but the serve starts and doesn't seem to re-route my sp requests correctly 

> Error: Registry editing has been disabled by your administrator

Wondering if there is a workaround for the above error.

Thanks

**Comment by koltyakov** [comment]
Hi @tarundhillon,

I have not seen such error before and TBH not sure it comes from sp-rest-proxy as it does nothing with the registry.
Where this error does appear? In which console? If to open proxy workbench, does it work and able to send a request to SharePoint?

**Comment by koltyakov** [comment]
I guess I know what it might be. There is a registry key read (`QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography /v MachineGuid`, getting machine key) in one of the dependencies which secure locally stored passwords, but it always read-only. Let me think how this can be confirmed with a test case,

**Comment by koltyakov** [comment]
Could you try defining dummy `masterKey` in proxy init settings?

```typescript
const RestProxy = require('sp-rest-proxy');

const settings = {
  authConfigSettings: {
    masterKey: 'proxy',
    // encryptPassword: false // this also can be tried
  }
};

const restProxy = new RestProxy(settings);
restProxy.serve();
```

**Comment by tarundhillon** [comment]
Thanks @koltyakov !! Adding master key worked and I dont get the error anymore.

**Comment by koltyakov** [comment]
Cool! Happy coding!
