### ISSUE TITLE
Access has been blocked by Conditional Access policies.

### ISSUE THREAD

**Issue by dudi44** [koltyakov/sp-rest-proxy#96]
I get the following response during requesting my tenant by sp-rest-proxy:
{
  "readyState": 4,
  "responseText": "<S:Fault>\n  <S:Code>\n    <S:Value>S:Sender</S:Value>\n    <S:Subcode>\n      <S:Value>wst:FailedAuthentication</S:Value>\n    </S:Subcode>\n  </S:Code>\n  <S:Reason>\n    <S:Text xml:lang=\"en-US\">Authentication Failure</S:Text>\n  </S:Reason>\n  <S:Detail>\n    <psf:error xmlns:psf=\"http://schemas.microsoft.com/Passport/SoapServices/SOAPFault\">\n      <psf:value>0x80048823</psf:value>\n      <psf:internalerror>\n        <psf:code>0x80048823</psf:code>\n        <psf:text>AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.</psf:text>\n      </psf:internalerror>\n    </psf:error>\n  </S:Detail>\n</S:Fault>",
  "status": 400,
  "statusText": "Bad Request"
}

Used strategy is UserCredentials and for the same user and password  directly call to this tenant from browser works fine.

Why does proxing from localhost:3000 -> localhost:8080 -> tenant rise this issue?

Is additional setting by which I could workaround the issue without changing Policy Azure AD on the given account?

I can write that a few months ago it worked fine. I believe  Policy Azure AD had to be changed in the meantime and I would not like to overwrite Policy Azure AD

**Comment by koltyakov** [comment]
Hi @dudi44, 

The short answer is. Nope, you can't work around it client-side, only by policies on the tenant level, otherwise, CAS didn't make sence.

But you can try alternative authentication strategies, [this thread](https://github.com/koltyakov/sp-rest-proxy/issues/94) might be helpful.
