### ISSUE TITLE
Request has been deprecated.  You should consider moving to another HTTP Library.

### ISSUE THREAD

**Issue by NotMoni** [koltyakov/sp-rest-proxy#97]
Hey,

It looks like you use the request package in your code.
Request has been deprecated. 
Request package is unmaintained and will no longer be updated by the publisher.
You should switch to another HTTP request library for Node.js

Some other Library:
[Node-fetch](https://www.npmjs.com/package/node-fetch)
[Got](https://www.npmjs.com/package/got)
[Axios](https://www.npmjs.com/package/axios)

**Comment by koltyakov** [comment]
Thanks! I know. It’s planned to replace request dependency with node-fetch in future. Deprecated doesn’t mean something should be reimplemented immediately, also it’s a dependency of one of the dependencies as well and deprecation warning won’t go as easy.

**Comment by NotMoni** [comment]
ok.
