### ISSUE TITLE
Smartcard / ADFS / MFA

### ISSUE THREAD

**Issue by kayodebristol** [koltyakov/sp-rest-proxy#98]
The current authentication strategies don't seem to present an option that's compatible with MFA. Maybe I'm missing something? 

In terms of PnP PowerShell, I would use: 
Connect-PnPOnline -url https://My.SharePointSite.com -UseWebLogin

Is there a similar option for sp-rest-proxy, and if not, how can I help get it included?

**Comment by koltyakov** [comment]
Hi there,

Yes, there is a similar option in node-sp-auth - the library which is used for the authentication under the hood.

[On-Demand](https://github.com/s-KaiNet/node-sp-auth/wiki/On-demand-authentication) auth strategy is the same as web login.

**Comment by kayodebristol** [comment]
Thanks, although On-Demand didn't quite work... it's really close. 

- It uses Electron to navigate to "siteUrl"
- Electron then authenticates me with SharePoint [I'm In!]

This is where -useWeblogin would close the browser (electron in this case) and return session cookie (or something like that). In my case, the electron window doesn't close automatically. Forcing it closed give the following error: 

Response Error: 
```json
{
  "readyState": 4,
  "responseText": "Cannot read property '1' of null",
  "status": 400,
  "statusText": "Bad Request"
}
```

I'm still missing something. Any thoughts?

**Comment by koltyakov** [comment]
It can be because of the Electron version. I guess they break something in Electron API.
Please check the version `electron -v`. Last time I use On-Demand I experience something similar and after rolling back to Electron v6 it worked for me. So I didn't post an issue to `node-sp-auth` repo or dig into the problem deeper.

**Comment by kayodebristol** [comment]
Yes, v6 works for me. Thanks. Guess I need to followup with node-sp-auth. I hate not being able to use the latest version. I'm stuck on PnP.js 1.3.10 because of the IE crisis, and I hate it. 

Thanks again.

**Comment by kayodebristol** [comment]
@koltyakov I decided to integrate electron, pinned at v6, into the project template by default. Might save someone time and tears down the road. [Dev starter kit](https://GitHub.com/sp-svelte/template) targeting SharePoint development with svelte. But, the same paradigm could be used to target SP development with other frameworks. Thanks again.

**Comment by koltyakov** [comment]
Electron is an optional dependency for a reason. It’s needed only in 1-5% of the cases. And it’s huge. So installing it on demand and as a global dependency is by design. 

What’s really should be done is to place some details in node-sp-auth project’s docs (which versions are supported) or check if support for the new versions is feasible.

**Comment by kayodebristol** [comment]
Understand node-sp-auth, electron, optional dependency. 
But I hope that you can appreciate that the template I mentioned works in IE 10 (> 0.25%), it works with smartcard auth, it works with SharePoint 2013, it works with SharePoint Online. The developer's I'm trying to help will probably never know or care what node-sp-auth is. Wide support and ease of use at the cost of additional storage seems justified IMO. But, I haven't given up on getting the electron compatibility issue fixed.

**Comment by koltyakov** [comment]
Interested in taking a look at the template (the URL above is broken). Anyways, it's cool that you use our projects as dependencies, thank you that's really appreciated.

**Comment by kayodebristol** [comment]
https://github.com/sp-sveltejs/template

Sorry about that.
